### ISSUE TITLE
Players completely inmobile, frozen on occasions.

### ISSUE THREAD

**Issue by GazpaNova** [DRE2N/DungeonsXL#1002]
I've had this issue for some time already, and from what I was told, the error was somehow related to DungeonsXL not being compatible with WorldGuardExtraFlags.

I don't know what could I do. At random, a group in a DXL simply suffers from this. I have to restart my server: My players disconnecting don't fix the issue.

The console simply gets filled with this while the frozen players are frozen and online:

[21:34:01] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:01] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:01] [Server thread/WARN]: [WorldGuard] Task #91 for WorldGuard v7.0.4+f7ff984 generated an exception
java.lang.NullPointerException: null
[21:34:01] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:01] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:01] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/INFO]: Drako issued server command: /sit
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/WARN]: [WorldGuard] Task #91 for WorldGuard v7.0.4+f7ff984 generated an exception
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:02] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/WARN]: [WorldGuard] Task #91 for WorldGuard v7.0.4+f7ff984 generated an exception
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:03] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:04] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
[21:34:04] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null

[21:09:23] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.4+f7ff984
java.lang.NullPointerException: null
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.AbstractRegionManagerWrapper.getRegion(AbstractRegionManagerWrapper.java:21) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.wg.WorldGuardUtils.createFlagValueCalculator(WorldGuardUtils.java:89) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.wg.WorldGuardUtils.queryValueUnchecked(WorldGuardUtils.java:68) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnEntryFlagHandler.onCrossBoundary(TeleportOnEntryFlagHandler.java:48) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.HandlerWrapper.onCrossBoundary(HandlerWrapper.java:59) ~[?:?]
	at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:220) ~[?:?]
	at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:180) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:424) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor342.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:803) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:515) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:844) ~[?:?]
	at de.erethon.dungeonsxl.DungeonsXL$1.lambda$run$0(DungeonsXL.java:418) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at de.erethon.dungeonsxl.DungeonsXL$1.run(DungeonsXL.java:418) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1268) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-"d3ee222"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[latest.log](https://github.com/DRE2N/DungeonsXL/files/6268611/latest.log)

If you want my full startup logs, they're here, too.

**Comment by Sataniel98** [comment]
If you don't get the WorldGuard NPEs in other situations where DXL teleports players into instance worlds (like e.g. with teleport signs, dungeon portals, /dxl play) you can ignore them as they have nothing to do with the "freezing" itself and most likely won't occur once that's resolved. If you do, please report the error to their developers.

For the time being, /dxl reload should fix the problem. (The command will be available again)
