### ISSUE TITLE
Console getting spammed with errors.

### ISSUE THREAD

**Issue by KingOfMyGames** [DRE2N/DungeonsXL#1004]
**Description**

So I updated the plugin to the latest version, and now I noticed that whenever an event happens the console gets spammed. I'll include some of the things it spams in this bug report.

**Reproduce**

1. Enter a dungeon (in my case one that was made in the previous version of the plugin, not sur if that matters)
2. Add a mob summon sign, [mob]/zombie/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the spawn sign
6. Not sure what triggerd the second error, but I suppose the event name SignChangeEvent would mean something to you.

**Expected behavior**

Literally nothing. No feedback text or anything. thats what I would expect.

**Screenshots / GIFs / videos**
```
[12:49:36] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to DungeonsXL v0.18-SNAPSHOT-1087
java.lang.NullPointerException: null
	at de.erethon.dungeonsxl.world.DWorldListener.onTouch(DWorldListener.java:229) ~[?:?]
	at de.erethon.dungeonsxl.world.DWorldListener.onEntityDamage(DWorldListener.java:199) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor571.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:954) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:910) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1099) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1838) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1166) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:256) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1085) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1857) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2249) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
The above one gets spammed very often while fighting a mob.
And another slightly different one:
```
[12:51:32] [Server thread/ERROR]: Could not pass event SignChangeEvent to DungeonsXL v0.18-SNAPSHOT-1087
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
	at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
	at java.lang.String.substring(String.java:1874) ~[?:?]
	at de.erethon.dungeonsxl.sign.DSignListener.onSignChange(DSignListener.java:108) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor591.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2813) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$18(PlayerConnection.java:2766) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:324) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:338) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1200) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-"3dadd97bb"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Relevant configuration files**

none

**Comment by Sataniel98** [comment]
Thank you for the report. The problems should be fixed, I'll upload the changes when I've tested them.
