### ISSUE TITLE
Spaming error in console

### ISSUE THREAD

**Issue by fillnati** [DRE2N/DungeonsXL#1021]
[14:44:26 ERROR]: Could not pass event PlayerInteractEntityEvent to DungeonsXL v0.18-SNAPSHOT-1087
java.lang.AbstractMethodError: Method me/petomka/armorstandeditor/util/EntityLocationProxy.getPersistentDataContainer()Lorg/bukkit/persistence/PersistentDataContainer; is abstract
        at me.petomka.armorstandeditor.util.EntityLocationProxy.getPersistentDataContainer(EntityLocationProxy.java) ~[?:?]
        at de.erethon.caliburn.CaliburnAPI.getExMobId(CaliburnAPI.java:605) ~[?:?]
        at de.erethon.caliburn.CaliburnAPI.getExMob(CaliburnAPI.java:572) ~[?:?]
        at de.erethon.caliburn.listener.MobListener.onPlayerInteract(MobListener.java:136) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor809.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-602]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-602]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-602]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-602]
        at me.petomka.armorstandeditor.Main.lambda$isInteractCancelled$0(Main.java:137) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528) ~[?:?]
        at me.petomka.armorstandeditor.Main.isInteractCancelled(Main.java:140) ~[?:?]
        at me.petomka.armorstandeditor.handler.ArmorStandEditHandler.onAdjustmentMade(ArmorStandEditHandler.java:247) ~[?:?]
        at me.petomka.armorstandeditor.listener.ArmorStandEditListener.onItemHeld(ArmorStandEditListener.java:188) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-602]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-602]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-602]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1907) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-602]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-602]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Sataniel98** [comment]
ArmorStandEditor is outdated, please report this to them.
