### ISSUE TITLE
error up to date

### ISSUE THREAD

**Issue by LoneDevilX** [DRE2N/DungeonsXL#1036]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
Using latest paper v1.17 dev 71, DungeonsXL v0.18-SNAPSHOT-1097
start server, and it shows an error
(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**
1. start server

**Expected behavior**
should be load.

**Screenshots / GIFs / videos**

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```
[22:04:43] [Server thread/INFO]: [DungeonsXL] Enabling DungeonsXL v0.18-SNAPSHOT-1097
[22:04:43] [Server thread/INFO]: [DungeonsXL] [##########[DungeonsXL]##########]
[22:04:43] [Server thread/INFO]: [DungeonsXL] Internals: [v1_17_R1]
[22:04:43] [Server thread/INFO]: [DungeonsXL] Paper API: [true]
[22:04:43] [Server thread/INFO]: [DungeonsXL] Economy: [true]
[22:04:43] [Server thread/INFO]: [DungeonsXL] Permissions: [true]
[22:04:43] [Server thread/INFO]: [DungeonsXL] Metrics: [https://bstats.org/plugin/bukkit/DungeonsXL/1039]
[22:04:43] [Server thread/INFO]: [DungeonsXL] SpigotMC ID: [9488]
[22:04:43] [Server thread/INFO]: [DungeonsXL] [###############################]
[22:04:43] [Server thread/WARN]: [DungeonsXL] Support for Minecraft 1.14 and higher is experimental. Do not use this in a production environment.
[22:04:43] [Server thread/ERROR]: Error occurred while enabling DungeonsXL v0.18-SNAPSHOT-1097 (Is it up to date?)
java.lang.NoClassDefFoundError: de/erethon/caliburn/CaliburnAPI
	at de.erethon.dungeonsxl.DungeonsXL.loadCaliburn(DungeonsXL.java:293) ~[?:?]
	at de.erethon.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:249) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-71]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-71]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-71]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-71]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-71]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-71]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: de.erethon.caliburn.CaliburnAPI
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-71]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 12 more
```

**Comment by Sataniel98** [comment]
DXL isn't for 1.17.
