### ISSUE TITLE
cannot use the plugin

### ISSUE THREAD

**Issue by lord44210** [DRE2N/DungeonsXL#106]
Hello,

Today I tried the plugin on a modded server. I've created a dungeon and when I use the command /dxl edit test1 I just have an error :  An internal error occured while attemping to perform this command.
and in the console I have this

[22:02:55] [Server thread/WARN]: [DungeonsXL] Task #35 for DungeonsXL v0.13 generated an exception

java.lang.NullPointerException

```
at io.github.dre2n.dungeonsxl.world.EditWorld.getByWorld(EditWorld.java:310) ~[?:?]

at io.github.dre2n.dungeonsxl.player.DEditPlayer.update(DEditPlayer.java:165) ~[?:?]

at io.github.dre2n.dungeonsxl.task.UpdateTask.run(UpdateTask.java:31) ~[?:?]

at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-R0.1-SNAPSHOT]

at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-R0.1-SNAPSHOT]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

[22:02:56] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to DungeonsXL v0.13

org.bukkit.event.EventException

```
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:272) [CraftEventFactory.class:1.7.10-R0.1-SNAPSHOT]

at net.minecraft.world.World.addEntity(World.java:1762) [ahb.class:?]

at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:212) [aho.class:?]

at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:258) [mt.class:?]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Caused by: java.lang.NullPointerException

```
at io.github.dre2n.dungeonsxl.world.EditWorld.getByWorld(EditWorld.java:310) ~[?:?]

at io.github.dre2n.dungeonsxl.listener.EntityListener.onCreatureSpawn(EntityListener.java:66) ~[?:?]

at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]

... 12 more
```

Please help me I really need this plugin for my server

thanks you in advance and sorry for my poor english

**Comment by Sataniel98** [comment]
At least the first one looks similar to an error I've noticed after doing /reload instead of restarting the server. Is it possible that you used /reload or a plugin like Plugman to reload DungeonsXL instead of stopping and restarting the server? And which is your server software and version?

**Comment by lord44210** [comment]
I always restart my server, I tried to reinstall the plugin but it didn't worked. I use KCauldron version  1647.201

**Comment by lord44210** [comment]
I noticed when I reinstall the plugin I can create one dungeon but it's always at the same place (not a new world/instance) and after having created my dungeon (with /dxl create) I cannot use other commands

**Comment by Sataniel98** [comment]
It probably won't work anyways with a Forge-based server. KCauldron uses completely different mappings...

**Comment by lord44210** [comment]
oh... thanks you
