### ISSUE TITLE
Mythic Mobs NPE

### ISSUE THREAD

**Issue by PaintsplattersMC** [DRE2N/DungeonsXL#1069]
[2021-11-11-1.log](https://github.com/DRE2N/DungeonsXL/files/7523439/2021-11-11-1.log)

Sorry about the 17 mb file.

I have no idea how to reproduce this error. But either during or a while after either dxl test or dxl edit, this starts happening.

![2021-11-11_15 57 36](https://user-images.githubusercontent.com/83564809/141374401-68e5ec2b-3f6f-4525-b215-3a1f73d7a0e3.png)
![2021-11-11_16 01 40](https://user-images.githubusercontent.com/83564809/141374405-5278803f-3dcb-4c2a-990d-0329cf713735.png)

I will report this to MM authors as well

**Comment by PaintsplattersMC** [comment]
paper 1.17.1 375

DXL latest spigot build as of posting date. same for ITems XL
MM Premium 5.0.0

**Comment by PaintsplattersMC** [comment]
Sorry to seem urgent but this issue makes this plugin totally unusable.

**Comment by Sataniel98** [comment]
Well, I can't read this on my phone, so please post the the actual error. Is the world on the screenshot a dungeon, or does natural spawning in other worlds go haywire?

**Comment by PaintsplattersMC** [comment]
MM Random spawning goes haywire

**Comment by PaintsplattersMC** [comment]
[21:36:46] [Server thread/ERROR]: [MythicMobs] [31m[SCHEDULER] Exception thrown whilst executing task[37m
[21:36:46] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
[21:36:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24)
[21:36:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:348)
[21:36:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getBiome(CraftRegionAccessor.java:202)
[21:36:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getBiome(CraftBlock.java:335)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitWorld.getLocationBiome(BukkitWorld.java:265)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.adapters.AbstractLocation.getBiome(AbstractLocation.java:451)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.conditions.all.BiomeCondition.check(BiomeCondition.java:41)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.skills.SkillCondition.evaluateRandomSpawnPoint(SkillCondition.java:217)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.spawning.random.RandomSpawner.checkSpawn(RandomSpawner.java:217)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.spawning.random.RandomSpawnerManager.doSpawns(RandomSpawnerManager.java:210)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.spawning.random.RandomSpawnerManager.lambda$spawnMobs$0(RandomSpawnerManager.java:193)
[21:36:46] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
[21:36:46] [Server thread/WARN]: 	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5669)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.spawning.random.RandomSpawnerManager.spawnMobs(RandomSpawnerManager.java:192)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.clock.MythicMobsClock.run(MythicMobsClock.java:39)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToConsumer.accept(Delegates.java:93)
[21:36:46] [Server thread/WARN]: 	at MythicMobs-5.0.0-SNAPSHOT.jar//io.lumine.xikage.mythicmobs.utils.Schedulers$LumineTask.run(Schedulers.java:162)
[21:36:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:36:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:36:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1564)
[21:36:46] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[21:36:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[21:36:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1279)
[21:36:46] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[21:36:46] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:36:46] [Server thread/ERROR]: [MythicMobs] [31m[SCHEDULER] Exception thrown whilst executing task[37m

**Comment by PaintsplattersMC** [comment]
this might be a MM issue. although touching DXL seems to trigger it

**Comment by Sataniel98** [comment]
DXL and MythicMobs technically don't interact with each other. I assume MythicMobs doesn't expect worlds to be  loaded / unloaded at runtime.

**Comment by PaintsplattersMC** [comment]
alright.
