### ISSUE TITLE
Console Stacktrace

### ISSUE THREAD

**Issue by RocketManKian** [DRE2N/DungeonsXL#1071]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

What I find weird about this error is everything still works according to plan, like I'm seeing no issue in game whatsoever until I looked at Console.

**Reproduce**

1. Have a [Ready] sign that teleports you to a location with a Start Sign and Mob Sign.
2. The Mob Sign has a D8 Trigger
3. The Start sign has a T1 trigger
4. The Trigger sign has a R1 and R2 Trigger

**Expected behavior**

No error to appear?

**Screenshots / GIFs / videos**

[13:41:33 INFO]: [DungeonsXL] Mob: An error occurred while triggering a sign of the type Mob. This is not a user error. Please report the following stacktrace to the developer of the plugin:
[13:41:33 INFO]: [DungeonsXL] A sign at -323, 64, 607 is erroneous!
[13:41:33 WARN]: java.lang.UnsupportedOperationException: Cannot set drop chance for PlayerInventory
[13:41:33 WARN]: at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryPlayer.setHelmetDropChance(CraftInventoryPlayer.java:325)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.mob.DMob.<init>(DMob.java:51)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.mob.CitizensMobProvider.summon(CitizensMobProvider.java:128)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL.wrapEntity(DungeonsXL.java:686)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.sign.windup.MobSign.spawn(MobSign.java:143)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.sign.windup.MobSpawnTask.run(MobSpawnTask.java:46)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.Windup.activate(Windup.java:138)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.Windup.trigger(Windup.java:166)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.Deactivatable.activate(Deactivatable.java:63)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:189)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.trigger.DistanceTrigger.onTrigger(DistanceTrigger.java:58)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:808)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.trigger.DistanceTrigger.triggerAllInDistance(DistanceTrigger.java:83)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL$1.lambda$run$0(DungeonsXL.java:414)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL$1.run(DungeonsXL.java:414)
[13:41:33 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL$1.lambda$run$0(DungeonsXL.java:414)
l.player.DGamePlayer.update(DGamePlayer.java:808)
[13:41:33 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL$1.run(DungeonsXL.java:414)
[13:41:33 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[13:41:33 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:41:33 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:41:33 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[13:41:33 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[13:41:33 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1564)
[13:41:33 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1279)
[13:41:33 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:41:33 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Sataniel98** [comment]
Thank you for the report, I'll fix it when I have time. For the time being, you can work around it by whitelisting player entities' item drops, e.g. like this in the main config:

```
default:
  damageProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME
  - PAINTING
  interactionProtectedEntities:
  - ARMOR_STAND
  - ITEM_FRAME
  mobItemDrops: # <= This
  - PLAYER
```

**Comment by RocketManKian** [comment]
New Error after adding this to the config as requested :)

[17:01:53 INFO]: [DungeonsXL] A sign at -155, 64, 297 is erroneous!
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.mob.DMob.getDrops(DMob.java:126)
[17:01:53 WARN]: java.lang.NullPointerException: Cannot invoke "de.erethon.caliburn.mob.ExMob.isSubsumableUnder(de.erethon.caliburn.mob.ExMob)" because "this.type" is null
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL.wrapEntity(DungeonsXL.java:686)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.mob.DMob.<init>(DMob.java:50)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.sign.windup.MobSign.spawn(MobSign.java:143)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.mob.CitizensMobProvider.summon(CitizensMobProvider.java:128)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.sign.windup.MobSpawnTask.run(MobSpawnTask.java:46)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.Windup.activate(Windup.java:138)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.Windup.trigger(Windup.java:166)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.Deactivatable.activate(Deactivatable.java:63)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:189)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.trigger.DistanceTrigger.onTrigger(DistanceTrigger.java:58)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.trigger.DistanceTrigger.triggerAllInDistance(DistanceTrigger.java:83)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:808)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL$1.lambda$run$0(DungeonsXL.java:414)
[17:01:53 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:01:53 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:01:53 WARN]: at dungeonsxl-dist-0.18-PRE-02.jar//de.erethon.dungeonsxl.DungeonsXL$1.run(DungeonsXL.java:414)
[17:01:53 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:01:53 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[17:01:53 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567)
[17:01:53 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[17:01:53 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[17:01:53 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
[17:01:53 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)

**Comment by Sataniel98** [comment]
Fixed
