### ISSUE TITLE
[DungeonsXL] Task #1772950 for DungeonsXL v0.18-PRE generated an exception

### ISSUE THREAD

**Issue by KieranCR** [DRE2N/DungeonsXL#1080]
I get this error when the dungeon tries to spawn in a MythicMobs Armor Stand entity 
It also will just spam the spawning of the entity so it will eventually spawn hundreds of them all on the same spot

You can reproduce this on the latest dev build by spawning an Armor Stand MM.

[Mob]
RPG2_SlimePit
1,1,MM
D 10

```
[21:30:48 WARN]: [DungeonsXL] Task #1772950 for DungeonsXL v0.18-PRE generated an exception
java.lang.IllegalArgumentException: Cannot set drop chance for non-Mob entity
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.inventory.CraftEntityEquipment.setDropChance(CraftEntityEquipment.java:260) ~[paper-1.18.1.jar:git-Paper-101]
        at org.bukkit.craftbukkit.v1_18_R1.inventory.CraftEntityEquipment.setHelmetDropChance(CraftEntityEquipment.java:215) ~[paper-1.18.1.jar:git-Paper-101]
        at de.erethon.dungeonsxl.mob.DMob.<init>(DMob.java:52) ~[dungeonsxl-dist-0.18-PRE.jar:?]
        at de.erethon.dungeonsxl.DungeonsXL.wrapEntity(DungeonsXL.java:707) ~[dungeonsxl-dist-0.18-PRE.jar:?]
        at de.erethon.dungeonsxl.sign.windup.MobSpawnTask.run(MobSpawnTask.java:48) ~[dungeonsxl-dist-0.18-PRE.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-101]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Sataniel98** [comment]
Thank you for the report. Fixed.

**Comment by KieranCR** [comment]
> Thank you for the report. Fixed.

This still seems to be an issue with the above error.

I compiled the fixed version which has your change:
`if (this.type.getSpecies().isAlive() && this.type != VanillaMob.PLAYER && !getDrops(gameWorld.getDungeon().getRules().getState(GameRule.MOB_ITEM_DROPS))) {` 

but the console error still persists and the armor stand mythic mob will keep spawning every second (without despawning).

```[22:03:56 WARN]: [DungeonsXL] Task #64231 for DungeonsXL v0.18-PRE generated an exception
java.lang.IllegalArgumentException: Cannot set drop chance for non-Mob entity
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.inventory.CraftEntityEquipment.setDropChance(CraftEntityEquipment.java:260) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at org.bukkit.craftbukkit.v1_18_R1.inventory.CraftEntityEquipment.setHelmetDropChance(CraftEntityEquipment.java:215) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at de.erethon.dungeonsxl.mob.DMob.<init>(DMob.java:52) ~[dungeonsxl-dist-0.18-PRE.jar:?]
        at de.erethon.dungeonsxl.DungeonsXL.wrapEntity(DungeonsXL.java:706) ~[dungeonsxl-dist-0.18-PRE.jar:?]
        at de.erethon.dungeonsxl.sign.windup.MobSpawnTask.run(MobSpawnTask.java:48) ~[dungeonsxl-dist-0.18-PRE.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1574) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1532]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Sataniel98** [comment]
Sorry for the long wait. Turns out armor stands are considered "alive"...
