### ISSUE TITLE
Is not compatible with paper 1.19.x

### ISSUE THREAD

**Issue by michaeltebo** [DRE2N/DungeonsXL#1102]
```
[01:00:55] [Server thread/INFO]: [DungeonsXL] [################################]
[01:00:56] [Server thread/ERROR]: Error occurred while enabling DungeonsXL v0.18-SNAPSHOT-1149 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/npc/NPCRegistry
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:197) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at de.erethon.dungeonsxl.mob.CitizensMobProvider.<init>(CitizensMobProvider.java:47) ~[dungeonsxl-dist-0.18-SNAPSHOT-1149.jar:?]
	at de.erethon.dungeonsxl.DungeonsXL.initCaches(DungeonsXL.java:379) ~[dungeonsxl-dist-0.18-SNAPSHOT-1149.jar:?]
	at de.erethon.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:249) ~[dungeonsxl-dist-0.18-SNAPSHOT-1149.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[paper-1.19.jar:git-Paper-20]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[paper-1.19.jar:git-Paper-20]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-20]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-20]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-20]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-20]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-20]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.npc.NPCRegistry
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 22 more
[01:00:56] [Server thread/INFO]: [DungeonsXL] Disabling DungeonsXL v0.18-SNAPSHOT-1149
```

**Comment by Sataniel98** [comment]
That's a problem of Citizens. Make sure you're running a build that loads successfully on your server.
