### ISSUE TITLE
Overloaded plugin world map is reset

### ISSUE THREAD

**Issue by 1470429149** [DRE2N/DungeonsXL#1114]
I was editing a map in the dxl plugin, after I typed dxl reload in the console, the map I was editing was cleared and a new configuration file was generated

[18:27:08 INFO]: WilledList11239 left the game
[18:27:28 WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[18:27:28 WARN]: [Multiverse-Core] To let Multiverse know about it, use:
[18:27:28 WARN]: [Multiverse-Core] /mv import DXL_Edit_0 NORMAL
[18:27:29 INFO]:                              
[18:27:29 INFO]:                            
[18:27:29 INFO]:                       
[18:27:29 INFO]:      
[18:27:29 INFO]:                                 [ 重新载入副本内容 ]
[18:27:29 INFO]: [NoSpawnChunks] Unloading chunks in world DXL_Edit_0...
[18:27:29 INFO]: [NoSpawnChunks] Unloaded 0 chunks. Took 2 ms.
[18:27:33 WARN]: [DungeonsXL] Task #13366 for DungeonsXL v0.18-PRE-02 generated an exception
java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
        at de.erethon.dungeonsxl.util.commons.misc.FileUtil.copyDir(FileUtil.java:82) ~[DXL副本.jar:?]
        at de.erethon.dungeonsxl.world.DEditWorld$2.run(DEditWorld.java:180) ~[DXL副本.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by 1470429149** [comment]
Forgive me if I can't describe it accurately, I'm in a hurry now, the map that my team took a week to build is emptied directly after dxl reload! ! ! And a configuration file suddenly appeared in the map/mapname storage map location: invitedPlayers:
- 7fd05b39-0c2f-392b-87d2-09c64138eb85
- 928c83cf-6694-3209-933f-14c912f0e615
- 4d7dcace-934f-39ff-80a0-c92219c673fa
-e62f68f0-2586-359b-b80a-fea21e74ca47
- 0d820063-a96a-3b57-8bbf-c051723cd85f
- 2f9a5d3a-5726-3525-865e-f45aa771cf12
- cd1595ac-5330-3442-9595-125b9721b11e
- 5e063fda-6f76-3ddc-b7b2-93ea2f9a108f
worldEnvironment: NORMAL
