### ISSUE TITLE
/dxl msg -- internal error

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#144]
/dxl msg

simply throw exception

[17:00:08] [Server thread/INFO]: test23 issued server command: /dxl msg 1 "test"
[17:00:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.14.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
    at io.github.dre2n.dungeonsxl.command.MsgCommand.onExecute(MsgCommand.java:90) ~[?:?]
    at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-9797151-301db84]

**Comment by wysohn** [comment]
DResourceWorld.java

at line 56

 File configFile = new File(folder, "config.yml");
        if (configFile.exists()) {
            config = new WorldConfig(configFile);
        }

it seems the newly created map will never generate the default config.yml?

or do I have to make my own config.yml manually everytime?

where is the example if that's the case?

**Comment by wysohn** [comment]
opps just found an example in the wiki

sorry :/

but it could be really nice if default yml will be generated

**Comment by Sataniel98** [comment]
Maps don't generate config files because maps don't need config files. All information can be fetched from other sources as well, like the default and override values in the dungeon config or the default values in the main config. Does the error occur with latest  builds, too?

**Comment by wysohn** [comment]
I'm using v0.14.4 and doubt if it's the latest version

the error occurs if there is no config.yml file

**Comment by Sataniel98** [comment]
Fixed it, thank you for the report!
Can't sync at the moment because of connection issues, though :C
