### ISSUE TITLE
dungeon config load fails

### ISSUE THREAD

**Issue by wysohn** [DRE2N/DungeonsXL#156]
java.lang.NullPointerException
    at io.github.dre2n.dungeonsxl.config.DungeonConfig.load(DungeonConfig.java:230) ~[?:?]
    at io.github.dre2n.dungeonsxl.config.DungeonConfig.<init>(DungeonConfig.java:52) ~[?:?]
    at io.github.dre2n.dungeonsxl.dungeon.Dungeon.<init>(Dungeon.java:37) ~[?:?]
    at io.github.dre2n.dungeonsxl.dungeon.Dungeons.<init>(Dungeons.java:43) ~[?:?]
    at io.github.dre2n.dungeonsxl.dungeon.Dungeons.<init>(Dungeons.java:34) ~[?:?]
    at io.github.dre2n.dungeonsxl.DungeonsXL.loadDungeons(DungeonsXL.java:450) ~[?:?]
    at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:269) ~[?:?]
    at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:139) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:417) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540) [spigot-1.10.2.jar:git-Spigot-9797151-301db84]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by wysohn** [comment]
tutorial.yml

startFloor: tutorial
endFloor: tutorialend
floors:
- tutorial2
- tutorial3

floorCount: 7
removeWhenPlayed: false
overrideValues:
  keepInventoryOnEnter: true
defaultValues:
  keepInventoryOnEnter: true
configVersion: 1

**Comment by Sataniel98** [comment]
Fixed :)
