### ISSUE TITLE
Error report when player right click "ready" sign

### ISSUE THREAD

**Issue by Daxxas** [DRE2N/DungeonsXL#174]
Error in console : 
`[13:22:46 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.15
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:887) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_101]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_101]
        at io.github.dre2n.dungeonsxl.player.DGroup.startGame(DGroup.java:663) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:695) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.ReadySign.ready(ReadySign.java:163) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.ReadySign.onPlayerTrigger(ReadySign.java:118) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:180) ~[?:?]
        at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:114) ~[?:?]
        at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:49) ~[?:?]
        at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:247) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
        ... 17 more
`

**Comment by Daxxas** [comment]
Error in pastebin : 
http://pastebin.com/dcBWGzQ7

**Comment by Daxxas** [comment]
Error with Multiverse : 
http://pastebin.com/DEY9KqxG

**Comment by Tiplish** [comment]
Hi, same problem for me. I try it many times and there is alwas the same error :(

**Comment by Sataniel98** [comment]
Regenerate your main config and add enough values to the color list.

**Comment by Tiplish** [comment]
You think that the problem is the configfile? If i use your exemple where there is Floor configfile and Dungeon configfile  exemples, next i add the values on the config file (in default), it will solve the problem?

**Comment by Sataniel98** [comment]
It should have nothing to do with the game rule part.

**Comment by Tiplish** [comment]
Hello, now it works fine for me thx :)

**Comment by Sataniel98** [comment]
Fixed in 0.15.1
