### ISSUE TITLE
DSavePlayer doesn't know how to store special ItemsXL skulls

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#20]
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.10-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:181) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:133) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentArray.representData(SafeRepresenter.java:202) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        at io.github.dre2n.dungeonsxl.player.DSavePlayer.save(DSavePlayer.java:142) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DSavePlayer.<init>(DSavePlayer.java:62) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DPlayer.<init>(DPlayer.java:75) ~[?:?]
        at io.github.dre2n.dungeonsxl.command.EditCommand.onExecute(EditCommand.java:35) ~[?:?]
        at io.github.dre2n.dungeonsxl.listener.CommandListener.onCommand(CommandListener.java:50) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot.jar:git-PaperSpigot-c725b9c-12698ea]
        ... 15 more

**Comment by Sataniel98** [comment]
Bukkit bug is a Bukkit bug.
