### ISSUE TITLE
How can I use the loot table properly?

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#222]
1. Hi. I have solved 1. block destruction issue and gave up on - 2. timer on boss bar /3. using 'W' trigger properly - since those two issues are less important. Thank you for the help.
I have some new questions about loot table system.
I tried to simply copy your example loot script and tried it but received some error saying '[23:45:00] [Server thread/ERROR]: Cannot load plugins\DungeonsXL\scripts\loottables\PvE1.txt
org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object'
So I tried to change the example script to very simple version so I could self-diagnose what was causing the error, but it still caused similar problem.
I will include A. error code from running the example scripty and B. simplified script with its error code.
Please review these and let me know what I should do to make loot table work for my DXL. Thanks!
also I am planning to add some customized mob drop items from the MythicMobs plugin into the loot table if possible. Please let me know anything you could tell us to make this possible.

2. I believe 'gamePermmions:' section of the config is not operating properly in my dungeon.
   I have latest versions of both the Vault and the PermissionsEX.
I wanted to place few specific items with unique lores in the dungeon so players could collect them as their field loot. In order to accomplish this, I needed some permissions to be given to the players in the dungeon. However, when I used the 'gamePermmions:' section to prepare these permissions, it did not operate properly. Permission itself is working propley since I checked it by giving the permissions to the players manually and seen it work fine. I will include the config file with that 'gamePermmions:' value that I inserted so you can reivew. Please let me know what can be done to make 'gamePermmions:' work properly under the config.

[Errors.zip](https://github.com/DRE2N/DungeonsXL/files/834387/Errors.zip)

**Comment by Sataniel98** [comment]
1.  This looks like a syntax error. Does http://www.yamllint.com/ show any errors if you paste your loot table there?

2. I'll have a look at it, thank you for the report :)

**Comment by NCSV** [comment]
1. I checked it. Valid YAML.

**Comment by Ecilpse** [comment]
I checked. But it says Valid YAML.

**Comment by Sataniel98** [comment]
Just noticed it: "PvE1.txt" is a .txt file while it should be a .yml file. YAMLlint doesn't care for file names :)

**Comment by Ecilpse** [comment]
I changed txt to yml file. But still have some error.
This error only occur when i placed Loottables in \plugins\DungeonsXL\scripts\loottables.


> [01:22:27] [Server thread/INFO]: Could not find compatible Factions plugin. The game type PVP_FACTIONS_BATTLEFIELD will not get enabled...[m
[01:22:27] [Server thread/ERROR]: Error occurred while enabling DungeonsXL v0.15.7-SNAPSHOT-08 (Is it up to date?)
java.lang.NullPointerException
	at io.github.dre2n.caliburn.item.UniversalItemStack.deserializeSimple(UniversalItemStack.java:142) ~[?:?]
	at io.github.dre2n.dungeonsxl.loottable.DLootTable.<init>(DLootTable.java:123) ~[?:?]
	at io.github.dre2n.dungeonsxl.loottable.DLootTable.<init>(DLootTable.java:103) ~[?:?]
	at io.github.dre2n.dungeonsxl.loottable.DLootTables.<init>(DLootTables.java:36) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.loadDLootTables(DungeonsXL.java:502) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:244) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:127) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[01:22:27] [Server thread/INFO]: [BossShopPro] Enabling BossShopPro v1.4.3

And gamePermmions problem is very serious problem to me.
Please check it as soon as possble Y_Y..

**Comment by Sataniel98** [comment]
That's because you use UniversalItemStack together with CraftBukkit 1.8.8.

https://github.com/DRE2N/DungeonsXL/wiki/legacy-support#caliburn-integration
