### ISSUE TITLE
get started - aaa help me make that work true =) many errors and not working like in wiki pages...

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#223]
1. tip help - would be awesome have example prefilled files and folders to see how that work.

2. how can i look in where map im?

3. when im in one floor and put /dxl create {name} - to create next map - that move me to spawn of that floor (may be that copy map but i dont know how look that).

4. when i put /dxl leave - that dont move me out from floor map. that show message: You have to join group first. - what is that?

5. how i can get info about self in that plugin?
some like  /dxl me - show in chat my currently floor and group or "none" if im not in any floor/group

what signs i need put to create group in main world and go to dungeon?
or i need put portal to lobby and after that make groups?
i dont understand =(

**Comment by WillPowerCraft** [comment]
any server with that plugin or video demonstration? =)

**Comment by WillPowerCraft** [comment]
whats show /dxl list about map status?

i have:

Map | Invited
GG-1 | false
GG-L | false

what that "false" mean???

**Comment by WillPowerCraft** [comment]
![image](https://cloud.githubusercontent.com/assets/23665302/23802462/7fa85a66-05c4-11e7-8fb3-4d21cbce2654.png)
i have that /dxl status

i have latest spigot and MM intalled builds.
why i see "X" n craftbukkit and MythicMobs? what i need do to allow thats?

**Comment by WillPowerCraft** [comment]
i see new folders on main server folder

what is that? for what that and how i can use that?

![image](https://cloud.githubusercontent.com/assets/23665302/23802599/e0b0de46-05c4-11e7-9af4-ce08e903e848.png)

**Comment by WillPowerCraft** [comment]
I have error on log may be thats help ure to help me ^ ^

`[16:39:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [Tspigot.jar:git-Spigot-283de8b-4316a8c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.game.Game.<init>(Game.java:98) ~[?:?]
	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:88) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Tspigot.jar:git-Spigot-283de8b-4316a8c]
	... 15 more`

**Comment by Sataniel98** [comment]
1. I used to have some, but they are outdated now and would cause more confusion than they'd help. Maybe I'll publish new ones when I have a new server.

2. Sorry, I didn't understand what you mean by this...

3. Better save & leave your map first.

4. I have seen some of your problems including this one in outdated versions and if I /reload the server or use a plugin manager like PlugMan to load DungeonsXL. Both causes fatal errors.

5. /dxl game and /dxl group show do some of this

**Comment by Sataniel98** [comment]
"false" means your not invited to edit this map. You can use /dxl invite [player] to invite users to edit a map. You can still edit all maps if you are OP.

**Comment by Sataniel98** [comment]
DXL's MythicMobs integration was created for MythicMobs 2.x and is not tested with MythicMobs 4.x. However, you can safely ignore both "x" if they don't cause problems.

**Comment by Sataniel98** [comment]
Those are instance folders. Copies of the worlds that you find in plugins/DungeonsXL/maps/...

This allows you to have different groups of players playing one dungeon simultaneously without interfering with each other. You can also edit the maps while players play them.
