### ISSUE TITLE
PLEASE [ExternalMob] >>>> [EM]

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#247]
Make pls Allias! that terrible to make 100500 signs mbs and every time [ExternalMob] !!!!!!!!!!

=((( pain fingers!!!

**Comment by WillPowerCraft** [comment]
![image](https://cloud.githubusercontent.com/assets/23665302/24016475/53aeb454-0a9d-11e7-81ad-9bd68c4f3533.png)

**Comment by Sataniel98** [comment]
Just use the stick tool and copy your signs.

**Comment by WillPowerCraft** [comment]
AAAAaaaa FANTASTIC!!!!

any way just for your know i using variables of every mob like

9x ZOMBIEZ with some ther hp dmg equip skills for better game feeling))

so thats 100+ signs was terrible aspecially when map stop saving and crash saves ((( when need do same work with signs again...

**Comment by WillPowerCraft** [comment]
i have error save floor every time when i put many sign-mobs and save floor!
stick help me now do that faster, but i do that 6th time today on one map... that hard and take many many time with out any result...

put 20+ signs
dxl save
dxl leave
dxl edit {map}
load crash - map crash
load backup
repeat...

log error:
```
[23:21:43 INFO]: -------- World Settings For [DXL_Edit_1] --------
[23:21:43 INFO]: Mob Spawn Range: 4
[23:21:43 INFO]: Cactus Growth Modifier: 100%
[23:21:43 INFO]: Cane Growth Modifier: 100%
[23:21:43 INFO]: Melon Growth Modifier: 100%
[23:21:43 INFO]: Mushroom Growth Modifier: 100%
[23:21:43 INFO]: Pumpkin Growth Modifier: 100%
[23:21:43 INFO]: Sapling Growth Modifier: 100%
[23:21:43 INFO]: Wheat Growth Modifier: 100%
[23:21:43 INFO]: NetherWart Growth Modifier: 100%
[23:21:43 INFO]: Vine Growth Modifier: 100%
[23:21:43 INFO]: Cocoa Growth Modifier: 100%
[23:21:43 INFO]: Entity Activation Range: An 12 / Mo 24 / Mi 2
[23:21:43 INFO]: Entity Tracking Range: Pl 48 / An 32 / Mo 32 / Mi 32 / Other 64
[23:21:43 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[23:21:43 INFO]: Random Lighting Updates: true
[23:21:43 INFO]: Structure Info Saving: true
[23:21:43 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[23:21:43 INFO]: Max TNT Explosions: 100
[23:21:43 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[23:21:43 INFO]: Item Despawn Rate: 3600
[23:21:43 INFO]: Item Merge Radius: 1.0
[23:21:43 INFO]: Arrow Despawn Rate: 1200
[23:21:43 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[23:21:43 INFO]: View Distance: 8
[23:21:43 INFO]: Zombie Aggressive Towards Villager: true
[23:21:43 INFO]: Experience Merge Radius: 2.0
[23:21:43 INFO]: Nerfing mobs spawned from spawners: false
[23:21:44 INFO]: Preparing start region for level 4 (Seed: 5953503457438110920)
[23:21:45 INFO]: Preparing spawn area for DXL_Edit_1, 12%
[23:21:46 INFO]: Preparing spawn area for DXL_Edit_1, 28%
[23:21:47 INFO]: Preparing spawn area for DXL_Edit_1, 44%
[23:21:48 INFO]: Preparing spawn area for DXL_Edit_1, 61%
[23:21:49 INFO]: Preparing spawn area for DXL_Edit_1, 73%
[23:21:50 INFO]: Preparing spawn area for DXL_Edit_1, 93%
[23:22:00 ERROR]: null
net.minecraft.server.v1_11_R1.ExceptionWorldConflict: Failed to check session lock for world located at ./DXL_Edit_0, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
	at net.minecraft.server.v1_11_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:85) ~[Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.World.checkSession(World.java:2804) ~[Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:1030) ~[Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.WorldServer.save(WorldServer.java:1000) ~[Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.unloadWorld(CraftServer.java:980) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.Bukkit.unloadWorld(Bukkit.java:491) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at io.github.dre2n.dungeonsxl.world.DEditWorld.delete(DEditWorld.java:167) [dungeonsxl-0.15.7-SNAPSHOT-08.jar:?]
	at io.github.dre2n.dungeonsxl.world.WorldUnloadTask.run(WorldUnloadTask.java:43) [dungeonsxl-0.15.7-SNAPSHOT-08.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [Tspigot.jar:git-Spigot-283de8b-aa522c9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[23:22:00 INFO]: Error: ./DXL_Edit_0 (No such file or directory)

```
