### ISSUE TITLE
Internal error occured

### ISSUE THREAD

**Issue by mirofox** [DRE2N/DungeonsXL#267]
Whats it mean and how can i get my giant dungeon back?

>[05:45:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/HologramsAPI
	at io.github.dre2n.dungeonsxl.sign.HologramSign.onInit(HologramSign.java:60) ~[?:?]
	at io.github.dre2n.dungeonsxl.sign.DSign.create(DSign.java:251) ~[?:?]
	at io.github.dre2n.dungeonsxl.sign.DSign.create(DSign.java:214) ~[?:?]
	at io.github.dre2n.dungeonsxl.config.SignData.deserializeSigns(SignData.java:123) ~[?:?]
	at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:223) ~[?:?]
	at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiateAsGameWorld(DResourceWorld.java:269) ~[?:?]
	at io.github.dre2n.dungeonsxl.game.Game.<init>(Game.java:97) ~[?:?]
	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:88) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.gmail.filoghost.holographicdisplays.api.HologramsAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at io.github.dre2n.dungeonsxl.sign.HologramSign.onInit(HologramSign.java:60) ~[?:?]
	at io.github.dre2n.dungeonsxl.sign.DSign.create(DSign.java:251) ~[?:?]
	at io.github.dre2n.dungeonsxl.sign.DSign.create(DSign.java:214) ~[?:?]
	at io.github.dre2n.dungeonsxl.config.SignData.deserializeSigns(SignData.java:123) ~[?:?]
	at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:223) ~[?:?]
	at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiateAsGameWorld(DResourceWorld.java:269) ~[?:?]
	at io.github.dre2n.dungeonsxl.game.Game.<init>(Game.java:97) ~[?:?]
	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:88) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	... 15 more

**Comment by Sataniel98** [comment]
You need HolographicDisplays to use holograms.

**Comment by Sataniel98** [comment]
Fixed.
