### ISSUE TITLE
[Urgent] Plugin Broken

### ISSUE THREAD

**Issue by mirofox** [DRE2N/DungeonsXL#268]
The dungeon froze, and the plugin crashed, now it won't let me edit, or explore it
`[04:01:59] [Server thread/ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
	at org.bukkit.Location.deserialize(Location.java:595) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at io.github.dre2n.dungeonsxl.util.commons.config.BRConfig.<init>(BRConfig.java:60) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.config.PlayerData.<init>(PlayerData.java:72) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.loadPlayerData(DGlobalPlayer.java:113) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.<init>(DGlobalPlayer.java:67) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.<init>(DGlobalPlayer.java:61) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.player.DPlayers.getByPlayer(DPlayers.java:44) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:55) [dungeonsxl-0.15.6.jar:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) [dungeonsxl-0.15.6.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[04:01:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.config.PlayerData.load(PlayerData.java:358) ~[?:?]
	at io.github.dre2n.dungeonsxl.config.PlayerData.<init>(PlayerData.java:77) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.loadPlayerData(DGlobalPlayer.java:113) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.<init>(DGlobalPlayer.java:67) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.<init>(DGlobalPlayer.java:61) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DPlayers.getByPlayer(DPlayers.java:44) ~[?:?]
	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:55) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-7d78b81-50acb44]
	... 15 more`

**Comment by Sataniel98** [comment]
Your player data seems to be corrupted. Remove it and it should work fine again.
