### ISSUE TITLE
Dungeons just broke -getStartLocation NullPointerException-

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#269]
I've already tried removing the Lobby sign, erasing my player data, rebooting the server don't know how many times, removing the bugged maps from the server folder, disabling Dynmap, nothing.
I don't have multiverse.
I can edit them but as soon as I try /dxl test or I join (or anyone else) a dungeon, sayonara. It worked properly since one hour ago while we're working (dxl test worked too) and then boom. I may had lag in the meanwhile 'cause I was downloading files but I hope people doesn't just need lag to break a plugin.

`[00:24:31 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.15.6
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[server.jar:git-Paper-1101]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1101]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1101]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-Paper-1101]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-Paper-1101]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:917) ~[server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[server.jar:git-Paper-1101]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [server.jar:git-Paper-1101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [server.jar:git-Paper-1101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.world.DGameWorld.getStartLocation(DGameWorld.java:169) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.respawn(DGamePlayer.java:707) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGroup.startGame(DGroup.java:816) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:693) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.ReadySign.ready(ReadySign.java:163) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.ReadySign.onPlayerTrigger(ReadySign.java:118) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:180) ~[?:?]
        at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:114) ~[?:?]
        at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:49) ~[?:?]
        at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:254) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor532.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[server.jar:git-Paper-1101]
        ... 18 more
>
`

**Comment by Sataniel98** [comment]
Doesn't make much sense to me (maybe because the line numbers of the old build don't match the current code anymore), try to regenerate the sign data and / or set a new start sign.
