### ISSUE TITLE
DGamePlayer instantiation NPE

### ISSUE THREAD

**Issue by HazielKaos** [DRE2N/DungeonsXL#272]
Got this error on console :
[DungeonsXL] Task #7707 for DungeonsXL v0.15.6 generated an exception 
java.lang.NullPointerException

**Comment by Sataniel98** [comment]
I'll need the whole stacktrace

**Comment by HazielKaos** [comment]
this is the full error display in the console :/

**Comment by HazielKaos** [comment]
After search in the .log files i found this

`[Server thread/WARN]: [DungeonsXL] Task #7707 for DungeonsXL v0.15.6 generated an exception
java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:64) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by HazielKaos** [comment]
hope it will be fixed soon

**Comment by Sataniel98** [comment]
I'm not working on this plugin at the moment, so maybe in a few months.

**Comment by Sataniel98** [comment]
Duplicate of #278
