### ISSUE TITLE
Error /dxl edit

### ISSUE THREAD

**Issue by DoctorWhoFR** [DRE2N/DungeonsXL#278]
Spam the console with that when i try command /dxl edit
[error.txt](https://github.com/DRE2N/DungeonsXL/files/1050674/error.txt)

**Comment by Sataniel98** [comment]
That's a known issue.

**Comment by DoctorWhoFR** [comment]
can you fix it ?

**Comment by Sataniel98** [comment]
Eventually yes. Don't expect anything in the forseeable future.

**Comment by Sataniel98** [comment]
```
[21:52:11 WARN]: [DungeonsXL] Task #3205 for DungeonsXL v0.15.6 generated an exception
java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:64) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
