### ISSUE TITLE
Broken with Spigot 1.12

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#282]
Tested with:
DungeonsXL v0.15.7-SNAPSHOT-08
Spigot 1.12 build 1304

It seems that spigot 1.12 has removed some api. According to the thread you may need to reconfigure the build scripts and re-build it with the new version. [Link to the thread is here](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre6-released.240317/).

Exception while loading:
```
java.lang.NullPointerException: null
	at io.github.dre2n.caliburn.item.UniversalItemStack.deserializeSimple(UniversalItemStack.java:142) ~[?:?]
	at io.github.dre2n.caliburn.item.UniversalItemStack.deserializeList(UniversalItemStack.java:120) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DClass.<init>(DClass.java:53) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DClass.<init>(DClass.java:45) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DClasses.<init>(DClasses.java:36) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.loadDClasses(DungeonsXL.java:488) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:243) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:127) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

You have been doing a great job, keep going!

**Comment by Sataniel98** [comment]
Thank you. I am aware of it, but I will not update before I take this plugin up again. I'd rather support my plugins or have them on hold, but nothing in between.

**Comment by Tiplish** [comment]
Hi Sataniel98. 

Indeed, you do a great job with this plugin but, it is possible to have an estimation on when you will focus on DXL? Week/month? We have a stable version with the other plugins that we use to manage dungeon and our server is 1.12 ready soon (thanks to the upgrad of the plugins that we used). But we will not go on 1.12 before DXL is upgrad to 1.12 :)

**Comment by Sataniel98** [comment]
I plan to get FactionsXL, which is the core of my server, stable until the end of this month when the server goes public. There'll be most likely some more work to do especially in the first few weeks, but I'm positive that I can continue to work on our quests / dungeons / RPG stuff then, which includes DXL.

**Comment by Tiplish** [comment]
Ok thanks for your informations :)

**Comment by Sataniel98** [comment]
In general, it should work with 1.12 except:
- Caliburn API features
- Performance tweaks (async world loading)
- Title / action bar messages will be sent as centered chat messages
- ResourcepackAPI doesn't support 1.12

**Comment by Tiplish** [comment]
We will try it soon.

**Comment by k-jiang** [comment]
I did "some" upgrade for you since I can wait no longer. Check the pull request https://github.com/DRE2N/DungeonsXL/pull/285

**Comment by Sataniel98** [comment]
Thank you, I appreciate it! However, there are a few problems with your PR:
- It is based on the 0.15.6 branch, while I am doing some major refactoring on the listener branch. That being said, I cannot easily merge it into the current 0.15.7 snapshots
- It still compiles against Caliburn 0.2.3 which doesn't support 1.12, so it wouldn't fix this issue. I think this is the only game breaking issue with 1.12

I'd like to do some cleanup stuff when I update. That includes
- a new GUI API (I guess you noticed that I deprecated / removed the old one from DRECommons)
- an update to the documentation
- I'll outsource the last NMS stuff in DXL and update to DRECommons 3
- I'll outsource my ResourcepackAPI patches into a new project
