### ISSUE TITLE
Error when /dxl leave command

### ISSUE THREAD

**Issue by Flashback083** [DRE2N/DungeonsXL#297]
Hello ! 
I have an issue when i do the /dxl leave in dungeon,
my item inventory come back but i have an error and im still in dungeon
I need to /spawn to leave the map
I have this errorlog : 

[00:27:15] [Server thread/INFO]: MayoSama issued server command: /dxl leave
[00:27:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.16-SNAPSHOT-01
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.setItemInOffHand(Lorg/bukkit/inventory/ItemStack;)V
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:327) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:491) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:469) ~[?:?]
	at io.github.dre2n.dungeonsxl.command.LeaveCommand.onExecute(LeaveCommand.java:83) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 13 more

Thanks !

**Comment by Flashback083** [comment]
Oh i just add this rules : 
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: true

and its work also this gamerule in "false" make the error i paste ^^

**Comment by Sataniel98** [comment]
It looks like your server uses MCP mappings. Do you use Cauldron or maybe Thermos? I have never tested DungeonsXL with it and can't guarantee that it doesn't fail gracefully. This error happens because DungeonsXL doesn't recognize your server software. It doesn't know that there is no off hand in Cauldron / Thermos 1.7.10 (which wouldn't be the case with Spigot or CraftBukkit 1.7.10) and therefore doesn't exclude this action. Other problems occur as a chain reaction.

**Comment by Flashback083** [comment]
its Thermos 1.7.10 yep and okay, also i hope its the only incompatibility with this command ^^
Thanks !
