### ISSUE TITLE
All data went lost

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#298]
Backups, maps, scripts, ANYTHING. Weeks of work turned into nothing.
The only error? This, when we stopped the server (nobody was inside any dungeon nor using any dxl function), but the folders were already gone. So when did it happen? What a nice question, since the previous log was perfectly immaculated. So here, out of the blue: awesome.

`[DungeonsXL] Disabling DungeonsXL v0.15.6
[16:32:21] [Server thread/ERROR]: Error occurred while disabling DungeonsXL v0.15.6 (Is it up to date?)
java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.global.GroupSign.save(GroupSign.java:232) ~[?:?]
	at io.github.dre2n.dungeonsxl.global.GlobalProtections.saveAll(GlobalProtections.java:119) ~[?:?]
	at io.github.dre2n.dungeonsxl.global.GlobalProtections.saveAll(GlobalProtections.java:101) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.saveData(DungeonsXL.java:286) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.onDisable(DungeonsXL.java:171) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[server.jar:git-Paper-1101]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [server.jar:git-Paper-1101]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [server.jar:git-Paper-1101]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [server.jar:git-Paper-1101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:347) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:481) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:688) [server.jar:git-Paper-1101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[16:32:21]`

Inadmissible

**Comment by Sataniel98** [comment]
Sorry to hear that - but DungeonsXL never deletes backups. There is nothing like a function to remove old backups that could potentially have gone haywire. As it says at the SpigotMC page, DungeonsXL is not really meant to be used in a production environment.

**Comment by ghost** [comment]
The problem aren't backups, it's that the plugin reset itself, every single folder has been overwritten with an empty one, thus everything = gone. We succesfuly managed to recover something via our personal backups, still we can't risk to experiment another reset again

**Comment by ghost** [comment]
I'd like to inform you that the mistake was mine, AKA I'm a complete idiot. The plugin never deleted anything, I'm deeply sorry
