### ISSUE TITLE
TweaksEnabled Error in 1.11.2

### ISSUE THREAD

**Issue by renzwei** [DRE2N/DungeonsXL#299]
When I set tweaksEnabled to true and join dungeon throw this, If I not able  tweak, sometimes join dungeon spawn in void world.
`2:48:11] [Craft Scheduler Thread - 174/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:51)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at io.github.dre2n.dungeonsxl.util.commons.worldloader.v1_11_R1.createWorld(v1_11_R1.java:186)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at io.github.dre2n.dungeonsxl.util.commons.worldloader.WorldLoader.createWorld(WorldLoader.java:70)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at io.github.dre2n.dungeonsxl.world.DResourceWorld$1.run(DResourceWorld.java:231)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[02:48:11] [Craft Scheduler Thread - 174/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by Sataniel98** [comment]
The performance tweaks are not supported, do not use them if you get errors like this.
