### ISSUE TITLE
When i put the commants nothing happens

### ISSUE THREAD

**Issue by FuaHwis** [DRE2N/DungeonsXL#308]
here is the log:

[Server thread/ERROR]: Error occurred while enabling DungeonsXL v0.15.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at io.github.dre2n.dungeonsxl.command.DCommands.<clinit>(DCommands.java:51) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.loadDCommands(DungeonsXL.java:367) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:281) ~[?:?]
	at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:140) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-33d5de3]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 15 more
[20:12:26] [Server thread/INFO]: [Banknotes] Enabling Banknotes v1.8.0

**Comment by Sataniel98** [comment]
You'll need to use Spigot.

**Comment by FuaHwis** [comment]
oh....it doesnt work with craftbukkit?is there any wy to work with craftbukkit?

**Comment by Sataniel98** [comment]
I'm looking forward to get it working again, but for now, it won't work. There is no actual benefit if you use CB anyway.

**Comment by FuaHwis** [comment]
ok thanks

**Comment by Sataniel98** [comment]
Fixed.
