### ISSUE TITLE
Do not send messages to offline players

### ISSUE THREAD

**Issue by benr233** [DRE2N/DungeonsXL#311]
Server thread/WARN]: [DungeonsXL] Task #31980 for DungeonsXL v0.15.6 generated an exception
java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.util.commons.util.messageutil.v1_9_R2.sendActionBarMessage(v1_9_R2.java:67) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.util.messageutil.MessageUtil.sendActionBarMessage(MessageUtil.java:232) ~[?:?]
	at io.github.dre2n.dungeonsxl.task.TimeIsRunningTask.run(TimeIsRunningTask.java:63) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by Sataniel98** [comment]
Should be fixed
