### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by ghost** [DRE2N/DungeonsXL#330]
When I use the command /dxl create {new} nothing happens and none of the other /dxl commands work for me. I have tried on a server running only dungeonsXL, am i using it wrong or do i need a supporting plugin?

Thanks

**Comment by Sataniel98** [comment]
Sounds like you're using the wrong server software, an outdated build of DungeonsXL or some configuration issue causes DXL not to start. In either way, I'll need a log in order to help you.

**Comment by ghost** [comment]
Here is the logs from startup using craftbukkit:1.12.2 and latest update of DungeonsXL
Thanks

[20:42:07 INFO]: Starting minecraft server version 1.12.2
[20:42:07 INFO]: Loading properties
[20:42:07 INFO]: Default game type: SURVIVAL
[20:42:07 INFO]: Generating keypair
[20:42:07 INFO]: Starting Minecraft server on *:25565
[20:42:07 INFO]: Using default channel type
[20:42:07 INFO]: This server is running CraftBukkit version git-Bukkit-61e0c69 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:42:07 INFO]: [DungeonsXL] Loading DungeonsXL v0.15.6
[20:42:07 INFO]: Preparing level "world"
[20:42:08 INFO]: Preparing start region for level 0 (Seed: 2189426954948291108)
[20:42:09 INFO]: Preparing spawn area: 78%
[20:42:09 INFO]: Preparing start region for level 1 (Seed: -8927865938854545851)
[20:42:10 INFO]: Preparing start region for level 2 (Seed: -8927865938854545851)
[20:42:10 INFO]: [DungeonsXL] Enabling DungeonsXL v0.15.6
[20:42:10 INFO]: [DungeonsXL] [Updater] Searching for updates.
[20:42:10 INFO]: [##########[DungeonsXL]##########]
[20:42:10 INFO]: Internals: [UNKNOWN]
[20:42:10 INFO]: Spigot API: [false]
[20:42:10 INFO]: UUIDs: [true]
[20:42:10 INFO]: Economy: [false]
[20:42:10 INFO]: Permissions: [false]
[20:42:10 INFO]: Metrics: [true]
[20:42:10 INFO]: SpigotMC ID: [9488]
[20:42:10 INFO]: [###############################]
[20:42:11 INFO]: Disabled performance tweaks because there is no support for this server software.
[20:42:11 INFO]: Could not find compatible Factions plugin. The game type PVP_FACTIONS_BATTLEFIELD will not get enabled...
[20:42:11 INFO]: Could not find compatible Citizens plugin. The mob provider Citizens ("CI") will not get enabled...
[20:42:11 ERROR]: Error occurred while enabling DungeonsXL v0.15.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at io.github.dre2n.dungeonsxl.command.DCommands.<clinit>(DCommands.java:51) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.loadDCommands(DungeonsXL.java:367) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:281) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:370) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-61e0c69]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        ... 15 more
[20:42:11 INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:42:11 INFO]: Done (3.128s)! For help, type "help" or "?"
[20:42:12 INFO]: [DungeonsXL] [Updater] Plugin is up-to-date.

**Comment by Sataniel98** [comment]
That's an issue with CraftBukkit which is already fixed in the latest builds. Besides that, v0.15.6 is not fully compatible with Minecraft 1.12.2. Update DungeonsXL.

**Comment by ghost** [comment]
How can i update the plugin if the latest release is 0.15.6?

**Comment by Sataniel98** [comment]
The SpigotMC resource thread is just a mirror for release builds. The main source is [my own server](
http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/).
