### ISSUE TITLE
Null Pointer Exception in PlayerInteractEvent

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#345]
When clicking the ready sign, a null pointer exception is invoked, here is the stack trace:
`Caused by: java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.world.DGameWorld.getStartLocation(DGameWorld.java:171) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.respawn(DGamePlayer.java:731) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGroup.startGame(DGroup.java:820) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:717) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:166) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:121) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:181) ~[?:?]
        at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:113) ~[?:?]
        at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
        at io.github.dre2n.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:61) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor664.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-latest.jar:git-Paper-1262]
        ... 18 more`

**Comment by Sataniel98** [comment]
Which version is this?

**Comment by arnhav** [comment]
I believe I am using snapshot version 0.16 - 08 (my server is running PaperSpigot 1.12.2)
