### ISSUE TITLE
playing dungeons causes errors, dosnt work

### ISSUE THREAD

**Issue by fenix12585** [DRE2N/DungeonsXL#35]
I am using spigot 1.8.8 and dxl snapshot 10 (latest stable build) I have also tried all the beta builds as well.

This is the error message that comes up every time a player hits the ready sign on the dungeon.
[10:19:36] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NumberFormatException: For input string: "loot"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_66]
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_66]
    at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_66]
    at io.github.dre2n.dungeonsxl.sign.ChestSign.onInit(ChestSign.java:34) ~[?:?]
    at io.github.dre2n.dungeonsxl.dungeon.game.GameWorld.startGame(GameWorld.java:94) ~[?:?]
    at io.github.dre2n.dungeonsxl.player.DGroup.startGame(DGroup.java:219) ~[?:?]
    at io.github.dre2n.dungeonsxl.player.DPlayer.ready(DPlayer.java:228) ~[?:?]
    at io.github.dre2n.dungeonsxl.sign.ReadySign.ready(ReadySign.java:71) ~[?:?]
    at io.github.dre2n.dungeonsxl.sign.ReadySign.onPlayerTrigger(ReadySign.java:50) ~[?:?]
    at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:129) ~[?:?]
    at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:85) ~[?:?]
    at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:27) ~[?:?]
    at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:231) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
    ... 18 more

I have tried to restart the server but that also dosnt work.

**Comment by Sataniel98** [comment]
Thank you.
"Caused by: java.lang.NumberFormatException: For input string: "loot"" - you have probably a weird sign in your game world.

**Comment by fenix12585** [comment]
Awesome! I will take a look at this and let you know by end of day today (eastern time) ---- On Mon, 15 Feb 2016 13:16:12 -0500  Daniel Saukelnotifications@github.com wrote ----Thank you."Caused by: java.lang.NumberFormatException: For input string: "loot"" - you have probably a weird sign in your game world.—Reply to this email directly or view it on GitHub.

**Comment by fenix12585** [comment]
So, i didnt have a sign like the one in the paste you gave me, In future versions, could you make improper signs blocked? I removed the loot sign and replaced it with chest... not sure why my builder used loot... is there such a sign? i dont see any in the wiki.

Thank you for helping with this! Everything works great again.

---- On Mon, 15 Feb 2016 13:16:12 -0500 Daniel Saukel &lt;notifications@github.com&gt;wrote ---- 

Thank you.

 "Caused by: java.lang.NumberFormatException: For input string: "loot"" - you have probably a weird sign in your game world.

**Comment by Sataniel98** [comment]
There is no such sign, but whether faulty or not, handling user input of any kind with a stacktrace is definitely a bug on my end; decent software must not fail gracefully because of minor setup errors. The bug will be fixed in the next release at SpigotMC.org. I'm not sure if I can get it done until then because of exams, but I try to release DXL 0.11 this month.

**Comment by fenix12585** [comment]
Thats great, in the mean time, now i understand what that means and should be able to resolve anything else that pops up until then :)
