### ISSUE TITLE
Tutorial problems

### ISSUE THREAD

**Issue by SnUncle** [DRE2N/DungeonsXL#352]
I set created a dungeon and use the turn on the tutorial 
but when the newbie come in my sever . did not have anything happend
im using luckperms 
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to DungeonsXL v0.16-SNAPSHOT-06
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.dungeon.Dungeon.<init>(Dungeon.java:52) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGroup.<init>(DGroup.java:135) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGroup.<init>(DGroup.java:105) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGroup.<init>(DGroup.java:100) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.startTutorial(DGlobalPlayer.java:378) ~[?:?]
	at io.github.dre2n.dungeonsxl.player.DPlayerListener.onPlayerJoin(DPlayerListener.java:374) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	... 14 more
[17:29:10] [Server thread/INFO]: SnUncle1117[/127.0.0.1:52793] logged in with entity id 1880 at ([world]-185.5, 70.0, 713.5)

**Comment by Sataniel98** [comment]
Thank you for your report. The bug is a missing check if the tutorial dungeon actually exists. That being said, the dungeon you selected as a tutorial doesn't seem to exist.

**Comment by SnUncle** [comment]
this dungeon is in my maps folder
