### ISSUE TITLE
can't hit mobs with config.yml

### ISSUE THREAD

**Issue by Gosselk** [DRE2N/DungeonsXL#358]
hi, 

I have a problem with the plugin. I can create a dungeon , the mobs spawn but I can't hit them and they can't hit me either.
Is it a bug ? Because I've not changed any config

**Comment by Sataniel98** [comment]
Did you set spawn-protection to 0 in your server.properties?

**Comment by Gosselk** [comment]
yes i did , and i added this file in my map folder : 
config.yml:

keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true

That is all ... 

ps: i've tried to create another dungeon with no config file. And in this dungeon I can fight with mobs.
But i need this config file or else my player is deprived of their stuff.

PS: if i can help with something

**Comment by Gosselk** [comment]
If i go in edit mode the mobs works correctly. But in play mode don't work .
My config file : 
https://pastebin.com/dKGYMUU8
List of my plugins:
https://image.ibb.co/mJe4qn/plugin_List.png

When i type this command /dxl reload , dungeon works again but the command /dxl leave doesn't.
it just leaves the group but not the map.

ps: when i'm start the server i have this : 

[17:11:40] [Server thread/INFO]: [##########[DungeonsXL]##########]
[17:11:40] [Server thread/INFO]: Internals: [UNKNOWN]
[17:11:40] [Server thread/INFO]: Spigot API: [true]
[17:11:40] [Server thread/INFO]: UUIDs: [true]
[17:11:40] [Server thread/INFO]: Economy: [true]
[17:11:40] [Server thread/INFO]: Permissions: [true]
[17:11:40] [Server thread/INFO]: Metrics: [true]
[17:11:40] [Server thread/INFO]: SpigotMC ID: [Number] <-- spigot ID
[17:11:40] [Server thread/INFO]: [###############################]

**Comment by Gosselk** [comment]
And when i try to reload (i try to help ) : 

[17:16:49] [Server thread/INFO]: orithas issued server command: /dxl reload
[17:16:49] [Server thread/INFO]: Disabled performance tweaks because there is no support for this server software.
[17:16:49] [Server thread/INFO]: Could not find compatible Factions plugin. The game type PVP_FACTIONS_BATTLEFIELD will not get enabled...
[17:16:49] [Server thread/INFO]: Could not find compatible Citizens plugin. The mob provider Citizens ("CI") will not get enabled...
[17:16:54] [Server thread/INFO]: dofo4589548 issued server command: /dxl play dj1
[17:16:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at io.github.dre2n.dungeonsxl.game.Game.<init>(Game.java:98) ~[?:?]
	at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:88) ~[?:?]
	at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81]
	... 15 more

**Comment by Gosselk** [comment]
The file config.yml is not the problem, when i write this in the main config file it's the same issue.
I wrote this : 
```
default:
    keepInventoryOnDeath: true
    keepInventoryOnEnter: true
    keepInventoryOnFinish: true
    keepInventoryOnEscape: true

```

**Comment by Gosselk** [comment]
I've try with different version of spigot 1.9.1 to 1.12.2 Same problem with all , and with just Vault , lucksperms, essential. 
In dungeon if i type this command "/dxl test", i now take damage and mobs too.

**Comment by Sataniel98** [comment]
You're several versions of DungeonsXL behind though. Does the issue occur with the latest build?

**Comment by Gosselk** [comment]
I have the 0.15.6 version , is the latest on spigot. is there another one ?

**Comment by Sataniel98** [comment]
http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl

**Comment by Gosselk** [comment]
same issue with the latest build, my error in console has disappear, but in dj i'm invincible and mobs/animals too ..
I have this on my console : 

[14:01:27] [Server thread/INFO]: [DungeonsXL] Enabling DungeonsXL v0.16-SNAPSHOT-09
[14:01:27] [Thread-17/INFO]: [DungeonsXL] [Updater] Searching for updates.
[14:01:27] [Server thread/INFO]: [##########[DungeonsXL]##########]
[14:01:27] [Server thread/INFO]: Internals: [v1_12_R1]
[14:01:27] [Server thread/INFO]: Spigot API: [true]
[14:01:27] [Server thread/INFO]: UUIDs: [true]
[14:01:27] [Server thread/INFO]: Economy: [true]
[14:01:27] [Server thread/INFO]: Permissions: [true]
[14:01:27] [Server thread/INFO]: Metrics: [true]
[14:01:27] [Server thread/INFO]: SpigotMC ID: [****] <-- spigot ID
[14:01:27] [Server thread/INFO]: [###############################]
[14:01:27] [Server thread/INFO]: Could not find compatible Factions plugin. The game type PVP_FACTIONS_BATTLEFIELD will not get enabled...
[14:01:27] [Server thread/INFO]: [DungeonsXL] Could not find compatible Citizens plugin. The mob provider Citizens ("CI") will not get enabled...
[14:01:27] [Thread-17/INFO]: [DungeonsXL] [Updater] Found new version: 0.15.6! (Your version is 0.16-SNAPSHOT-09)
[14:01:27] [Thread-17/INFO]: [DungeonsXL] [Updater] Download here: http://www.spigotmc.org/resources/9488

with /dxl test and /dxl edit it's work fine but /dxl play no ...
Maybe DungeonXL need an another plugin to work  ?

**Comment by Gosselk** [comment]
Any suggestion ? :) ( if i can help, say me how )

**Comment by Sataniel98** [comment]
There's actually nothing wrong in your startup log. Do you use a plugin to manage worlds?

**Comment by Gosselk** [comment]
Multiverse for creating world and worlguard. But when i test this with a new server with just : 
Vault, essential , LuckPerms it's the same thing.

1/ I create the dungeon with /dxl create dj1
2/ I leave the dungeon with /dxl leave
3/ I create a group like /dxl group create test
4/ I go in instance with /dxl play dj1

**Comment by Gosselk** [comment]
If else it's possible to create a sign with /dxl test command, until the command "/dxl play" is fixed?

**Comment by Sataniel98** [comment]
I can't reproduce your issue. This is not likely to be a bug. Are worlds called DXL_Game_* or similar registered by Multiverse?

**Comment by Gosselk** [comment]
Multiverse register no world , but i've see something i thing interesting. If i make /dxl list i see my dungeons like this 
dj1 : false
dj2 : false

This false is not the cause ? 
And if you want i can send you my test server for test this bug. with just 3 plugins.

ps: again sorry for my bad english

**Comment by Sataniel98** [comment]
That's a good idea, please send it. "false" refers to whether you are invited to edit this map. The list of invited players can be found inside the floor config.yml file, but it's irrelevant if you are OP or if you have the dxl.edit permission node.

PS: Don't worry, I've seen many way worse English skills since I started to program Minecraft plugins ^^ If that helps, I understand German and French as well (and Latin, lol)

**Comment by Gosselk** [comment]
Français à quel point ? :) 
This is my test server just for DungeonXL and i've teh same issue on this server and my server online.
https://ufile.io/iqxlk

**Comment by Sataniel98** [comment]
Bien que j'ai appris le français à l'école pour sept ans, je ne l'utilise pas souvent. Je fais des études d'histoire. De temps en temps, je lis des textes en français: Tout récemment par example, j'ai lis un livre au sujet de Charles le Téméraire, le duc de Bourgougne, pour une conférance. Alors, je comprends presque tout, mais je ne peux plus parler trop éloquemment.

And I have no clue about French gaming language or computer vocabulary, so maybe I'll just continue to answer in English and you write in whatever language you please? ^^

I had a look at your server setup. Since the existing ones were empty, I:
- Created a new dungeon using /dxl create dj2
- Added a ready sign. I didn't specify a game type
- Added a mob sign: [Mob] / Zombie / 1,1 / D 2
- Saved with /dxl save
- Left the map
- Played the map with /dxl play dj2
- Triggered the ready sign by punching it. The Zombie spawned

I was able to punch the Zombie without problems. I hope you noticed some difference to what you did, maybe about the game type?, because I have no idea what the reason for your problem could be :/

**Comment by Gosselk** [comment]
Tu parle vraiment bien français ! Bien joué ! quelques problèmes avec les temps ( conjugaisons), mais le français et quand même une des langues les plus dur ( même moi je fais pleins de fautes ).

Yes but i want my mobs to spawn with MythicMobs, i think it's work for you because you use a mob sign.
For my test, i have try with egg monsters. Or with the command of MythicMobs (for my official server). 

And yes i have a another difference is the ready sign. i'm trying tonight. 
Vielen Dank für Ihre Hilfe.

**Comment by Sataniel98** [comment]
Damn, it's "lu", isn't it? >.>

Gern geschehen! If you use /dxl test, the game starts immediately in the test game type. If you use /dxl play, the game does not start unless a ready sign is used. PvP / PvE is disabled in the lobby, and I am almost sure now that's your problem. Just didn't realize this because mobs aren't supposed to spawn there; mob signs don't enable before the game starts / a ready sign is triggered.

**Comment by Gosselk** [comment]
oui c'est bien "lu" ;)

the problem is i want to make a spawn of mob in edit mod(spawn with MythicMobs), no with signs. If i use this command /dxl play , the game start and the mobs is unhitable. Can i or can have make a sign in my dungeon with ready ? 
Thanks a lot for your help ;)

**Comment by Gosselk** [comment]
thanks a lot, with ready sign it's work fine. If you want help for something. you need to know i'm developper in web applications(with javascript). So don't hesitate to ask ;). And i'm glad to meet you.
Merci , danke , thank you. 

Ps : maybe you can be more precise in tutorial ( with ready , edit , play ).

**Comment by Sataniel98** [comment]
No problem, I'm glad I could help :) I agree that the wiki needs work.

Just note that mobs that aren't spawned through signs will not work with triggers and killing them will not be counted.

**Comment by Tiplish** [comment]
I don't know if it could help you for the first steps @Gosselk but : 
https://nefald.fr/wiki/DungeonsXL
Maybe it could help you. I have translate a part of the first steps for DXL in french
(I'm a french guy too :p )

**Comment by Sataniel98** [comment]
![](https://media.giphy.com/media/a3tiMmC4SKZpe/giphy.gif)

;D
