### ISSUE TITLE
NullPointerException on /dungeon play

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#361]
[14:22:36 INFO]: DungeonsXL - ERROR REPORT - NullPointerException
 #1: LINE 98 in FILE Game.java (io.github.dre2n.dungeonsxl.game.Game.<init>)
 #2: LINE 88 in FILE PlayCommand.java (io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute)
 #3: LINE 71 in FILE BRCommandExecutor.java (io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand)
 #4: LINE 44 in FILE PluginCommand.java (org.bukkit.command.PluginCommand.execute)
 #5: LINE 141 in FILE SimpleCommandMap.java (org.bukkit.command.SimpleCommandMap.dispatch)
 #6: LINE 89 in FILE CustomCommandMap.java (gyurix.commands.CustomCommandMap.dispatch)

**Comment by snowy6409** [comment]
Um also this.
![2018-02-19_17 24 52](https://user-images.githubusercontent.com/11221362/36399439-e0c67eaa-1599-11e8-87dd-deb2810cb8b8.png)

How are there two of me it seems it is not correctly removing me also I cant start the dungeon any more. I have to create a new one each time I want to play through it.


Says "The Group &v1 dose not exist"

**Comment by snowy6409** [comment]
Now i'm spammed with

[14:28:57 WARN]: [DungeonsXL] Task #40386 for DungeonsXL v0.15.6 generated an exception
java.lang.NullPointerException: null
        at io.github.dre2n.dungeonsxl.task.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:64) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-bacaf92]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-bacaf92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by Sataniel98** [comment]
Thank you for your report. I've had these kind of errors after unsafely reloading the plugin. Could this be the case? The stacktraces are not that helpful since the build you're running is outdated. Bugfixes have been applied to the play command since then.
