### ISSUE TITLE
NPE on every action

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#365]
Running the latest version of the plugin.

When I attempt to join an existing dungeon
```
[20:48:32 ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.16-SNAPSHOT-11
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:691) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_12_R1.WorldServer.<init>(WorldServer.java:60) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:950) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:471) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:223) ~[?:?]
        at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiateAsGameWorld(DResourceWorld.java:272) ~[?:?]
        at io.github.dre2n.dungeonsxl.global.DPortal.teleport(DPortal.java:210) ~[?:?]
        at io.github.dre2n.dungeonsxl.global.GlobalProtectionListener.onPlayerMove(GlobalProtectionListener.java:127) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor512.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-latest.jar:git-Paper-1262]
        ... 16 more
```

When I do `/dxl edit <mapName>` of an existing map
```
[20:55:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.16-SNAPSHOT-11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_12_R1.WorldServer.<init>(WorldServer.java:60) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:950) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:471) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:223) ~[?:?]
        at io.github.dre2n.dungeonsxl.world.DResourceWorld.instantiateAsEditWorld(DResourceWorld.java:265) ~[?:?]
        at io.github.dre2n.dungeonsxl.command.EditCommand.onExecute(EditCommand.java:70) ~[?:?]
        at io.github.dre2n.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Paper-1262]
        ... 15 more
```

When I do `/dxl reload`
```
[21:01:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dungeonsxl' in plugin DungeonsXL v0.16-SNAPSHOT-11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.world.DEditWorld.save(DEditWorld.java:122) ~[?:?]
        at io.github.dre2n.dungeonsxl.world.DWorldCache.saveAll(DWorldCache.java:248) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.saveData(DungeonsXL.java:251) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.onDisable(DungeonsXL.java:137) ~[?:?]
        at io.github.dre2n.dungeonsxl.command.ReloadCommand.onExecute(ReloadCommand.java:93) ~[?:?]
        at io.github.dre2n.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Paper-1262]
        ... 15 more
```

**Comment by Sataniel98** [comment]
Fixed it. Thank you for your report :) Build 12 should resolve the issues, sorry for all the trouble.

**Comment by arnhav** [comment]
Thank you for your quick response :) 👍
