### ISSUE TITLE
Internal Error on `/dxl reload`

### ISSUE THREAD

**Issue by arnhav** [DRE2N/DungeonsXL#368]
Apologies for yet another bug,

Running the latest version of the plugin. I just had just renamed a dungeon and I went to do `/dxl reload` and I had this error pop up on me:
```
[20:11:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.16-SNAPSHOT-12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1262]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1262]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.world.DEditWorld.save(DEditWorld.java:122) ~[?:?]
        at io.github.dre2n.dungeonsxl.world.DWorldCache.saveAll(DWorldCache.java:248) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.saveData(DungeonsXL.java:251) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.onDisable(DungeonsXL.java:137) ~[?:?]
        at io.github.dre2n.dungeonsxl.command.ReloadCommand.onExecute(ReloadCommand.java:93) ~[?:?]
        at io.github.dre2n.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Paper-1262]
        ... 15 more
```

**Comment by Sataniel98** [comment]
The latest builds are available [here](http://erethon.de/repo/de/erethon/dungeonsxl/). Thank you for your report.

**Comment by arnhav** [comment]
Awesome thank you!
