### ISSUE TITLE
Multiverse Inventory Problem

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#37]
Bei einem Server mit dem Plugin Multiverse Inventory versucht dieses ein eigenes Inventar anzulegen. Spieler die mit einer Diamantrüsstung in den Dungeon joinen haben diese auch wenn sie den Dungeon auch ohne Rüsstung betreten. Das einmalige Joinen reicht aus. Bekomme auch diese Fehlermeldung:

[18:00:43] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 36
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.api.DataStrings.parseInventory(DataStrings.java:421)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:20)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:10)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:76)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:283)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:90)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56)
[18:00:43] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183)
[18:00:43] [Server thread/WARN]:    at sun.reflect.GeneratedMethodAccessor643.invoke(Unknown Source)
[18:00:43] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:00:43] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerList.moveToWorld(PlayerList.java:684)
[18:00:43] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:468)
[18:00:43] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.teleport(CraftEntity.java:235)
[18:00:43] [Server thread/WARN]:    at io.github.dre2n.commons.util.playerutil.PlayerUtil.secureTeleport(PlayerUtil.java:77)
[18:00:43] [Server thread/WARN]:    at io.github.dre2n.dungeonsxl.player.DPlayer.<init>(DPlayer.java:131)
[18:00:43] [Server thread/WARN]:    at io.github.dre2n.dungeonsxl.global.DPortal.teleport(DPortal.java:200)
[18:00:43] [Server thread/WARN]:    at io.github.dre2n.dungeonsxl.listener.PlayerListener.onPortal(PlayerListener.java:405)
[18:00:43] [Server thread/WARN]:    at sun.reflect.GeneratedMethodAccessor684.invoke(Unknown Source)
[18:00:43] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:00:43] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:00:43] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerList.changeDimension(PlayerList.java:727)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityPlayer.c(EntityPlayer.java:551)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Entity.U(Entity.java:338)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityLiving.U(EntityLiving.java:179)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Entity.m(Entity.java:299)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1688)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityHuman.m(EntityHuman.java:142)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityPlayer.k_(EntityPlayer.java:254)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnection.c(PlayerConnection.java:138)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[18:00:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[18:00:43] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
[18:00:43] [Server thread/WARN]: [Multiverse-Inventories] Could not parse item: ItemStack{DIAMOND_BOOTS x 1}
[18:00:43] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 37 while parsing inventory
[18:00:43] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 38 while parsing inventory
[18:00:43] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 39 while parsing inventory
[18:00:44] [Server thread/WARN]: DuPleX_FD moved too quickly! -566.5169966211121,-57.0,15.699999988079071
[18:00:49] [Server thread/INFO]: DuPleX_FD issued server command: /dxl leave
[18:01:39] [Server thread/INFO]: [Multiverse-Core] World 'DXL_Game_0' was unloaded from memory.
[18:01:39] [Server thread/INFO]: [dynmap] Saved 1989 pending tile renders in world 'DXL_Game_0'

**Comment by DuPleXFD** [comment]
gut, ich habe jetzt das problem mit dieser option bei multiverseinventory gelöst:

# If set to true, any world not listed in a group will automatically use the settings for the default group!

  default_ungrouped_worlds: true

ob es jetzt ein bug war kann ich nicht sagen :/

**Comment by Sataniel98** [comment]
"ArrayIndexOutOfBoundsException: 36" dürfte ein interner Fehler von MultiverseInventories in 1.9, weil sich die Inventargröße mit dem Update geändert hat. Es würde mich sehr wundern, wenn der Fehler nur mit DungeonsXL auftritt. Die DungeonsXL-Methoden sind nur im Stacktrace aufgeführt, weil sie im selben Tick die Teleportation in die Dungeon-Map veranlasst haben:

> io.github.dre2n.commons.util.playerutil.PlayerUtil.secureTeleport(PlayerUtil.java:77)

Einen ähnlichen, bereits behobenen Fehler gab es in DungeonsXL bis Build 24 beim Lesen der savePlayer.yml. Ist zwar nicht in meiner Hand, aber die neusten Builds von Multiverse-Inventories sollten - wenn das Datum nicht täuscht - mit 1.9 laufen: http://ci.onarandombox.com/job/Multiverse-Inventories/
