### ISSUE TITLE
Cant figure out how to let players use their own inventory

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#385]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Explanation of the requested feature
Sharing inventory between world "Guilds" and DXL

### Possible use cases
Is it a problem with Perworldinventory or is it a setting in the config i am missing

**Comment by Sataniel98** [comment]
Don't know how this is a feature request, but does this help?
https://github.com/DRE2N/DungeonsXL/wiki/faq#how-can-i-make-it-so-that-players-play-dungeons-with-their-own-items

**Comment by snowy6409** [comment]
@Sataniel98 It worked for one run through of the dungeon but then I /stop the server and not it is not keeping the inventory anymore. My config.yml looks like this

`
forcedGameType: ADVENTURE
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnDeath: true
keepInventoryOnEscape: true
`





Also it is not throwing this error: 

`[17:42:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.15.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.game.Game.<init>(Game.java:98) ~[?:?]
        at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:88) ~[?:?]
        at io.github.dre2n.dungeonsxl.util.commons.command.BRCommandExecutor.onCommand(BRCommandExecutor.java:71) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        ... 15 more`

**Comment by Sataniel98** [comment]
Update to a more recent build please before posting errors, it is likely that your issue has already been fixed.

**Comment by snowy6409** [comment]
@Sataniel98 Quick question what is the loot tables file supposed to be named and is this correct for what it contains?
 
LootT1.yml

`0:

  item:
    ==: io.github.dre2n.caliburn.item.UniversalItemStack
    type: "CUSTOM_DEFAULT"
    material: "IRON_SWORD"
    durability: 35
    name: "&4CustomName"
    amount: 1
    lores:
     - "&4This is the first line."
     - "&6This is the second line."
    enchantments:
      "PROTECTION_ENVIRONMENTAL": 4
      "THORNS": 1
    attributes:
      name:
        type: "GENERIC_ATTACK_DAMAGE"
        slots:
          - "MAIN_HAND"
          - "HEAD"
        operation: "ADD_NUMBER"
        amount: 8.5
  chance: 75.0

`

**Comment by Sataniel98** [comment]
I obviously can't see if your indents are correct, but that seems like a one to one copy of the example in the wiki. You can really use anything as a name. Using "LootT1" as a name means you'll have to put "LootT1" in the third line of your chest sign.

https://github.com/DRE2N/DungeonsXL/wiki/signs#chest

By the way, please use separate issues per question. I kept this open to see if you answer after testing if your issue still occurs in a recent build.

**Comment by snowy6409** [comment]
It fixed it in the recent build
