### ISSUE TITLE
LootTables Throwing Error

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#387]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

Hello when I use the loot table script it throws the "Error" sign

![sign](https://user-images.githubusercontent.com/11221362/39605202-6114cb9c-4efd-11e8-85a2-8dfd0d3d8082.png)

[LootT1.txt](https://github.com/DRE2N/DungeonsXL/files/1972813/LootT1.txt)
Actually a .yml
located at (\plugins\DungeonsXL\scripts\loottables)

**Comment by Sataniel98** [comment]
"All chests in near by a chest sign become reward chests. When a player opens a reward chest in a dungeon, the content will be added to his group's reward inventory which contains items the players get in the main world of the server when they finish the dungeon."

You forgot the chest ^^

**Comment by snowy6409** [comment]
@Sataniel98 Ah I'm an idiot

**Comment by snowy6409** [comment]
@Sataniel98  Now the loot is working and saying it is added to the reward inventory but now it is not opening the reward menu to claim it. is there a command I am missing or did i do something wrong?

**Comment by snowy6409** [comment]
@Sataniel98 It also appears not that it is throwing a PlayerMoveEvent Exception to DungeonsXL when I finish it and am moving in the regular world.

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.github.dre2n.dungeonsxl.util.commons.gui.GUIButton`

**Comment by Sataniel98** [comment]
That's not a bug but a class loading error, is it possible that you reloaded DXL with /reload or a plugin like PlugMan? If so: Don't. Try a clean restart and let me know if the error still occurs.

**Comment by snowy6409** [comment]
@Sataniel98 Nope even with a /stop and then starting it again it still throws it.



`[18:57:51 ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.16-SNAPSHOT-612
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-21d5f75]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.github.dre2n.dungeonsxl.util.commons.gui.GUIButton
        at io.github.dre2n.dungeonsxl.util.commons.gui.PageGUI.newPage(PageGUI.java:93) ~[?:?]
        at io.github.dre2n.dungeonsxl.util.commons.gui.PageGUI.<init>(PageGUI.java:52) ~[?:?]
        at io.github.dre2n.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:118) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-2086bb0-21d5f75]
        ... 15 more`

**Comment by snowy6409** [comment]
@Sataniel98 It seems that it cant initialize the class is it there or is it missing?
