### ISSUE TITLE
Server spamming `Could not initialize class de.erethon.dungeonsxl.util.commons.gui.GUIButton`

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#400]
Occasionally my server is spamming tons of exceptions in the console while someone are playing dungeons. What does the `GUIButton` for? I never notice that DXL has GUI functionalities.

Server info:
PaperSpigot 1.12.2 build 1416
DungeonsXL 0.16 build from May 15th source code.
ItemsXL 0.2.5
Vault
zPermissions

```
[23:18:48 ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.16-SNAPSHOT
java.lang.NoClassDefFoundError: Could not initialize class de.erethon.dungeonsxl.util.commons.gui.GUIButton
        at de.erethon.dungeonsxl.util.commons.gui.PageGUI.newPage(PageGUI.java:93) ~[?:?]
        at de.erethon.dungeonsxl.util.commons.gui.PageGUI.<init>(PageGUI.java:52) ~[?:?]
        at de.erethon.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:118) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor828.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1416]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1416]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1416]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1416]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1416]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1416]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1416]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

Please let me know if you need more info. It's a great plugin please keep it on!

**Comment by k-jiang** [comment]
The exception continues even after players finished their dungeons :(
I have to `/dxl reload` to stop this.

**Comment by Sataniel98** [comment]
I'm aware of it, but I have no idea why this happens. The class definitely exists if you open the JAR as an archive. The GUI buttons that are stored inside [this class](https://github.com/DRE2N/DRECommons/blob/master/core/src/main/java/de/erethon/commons/gui/GUIButton.java). The used ones are the placeholders and the next / previous page buttons in reward inventories.

Duplicate of #390

**Comment by k-jiang** [comment]
Just had a peek on your code [here](https://github.com/DRE2N/DRECommons/blob/58fa6a610b738ec485ff5895c37d955c5ccaccc2/core/src/main/java/de/erethon/commons/gui/PageGUI.java#L93). Don't you need to do `GUIButton.PREVIOUS_PAGE` instead? Because it comes from another class. You need to either `new` it or access it through the class name if it is `static`. I guess this is why java addresses `NoClassDefFoundError` on this line.

Also, just saying, it seems that you are using something like [MHF's heads](https://minecraft.gamepedia.com/Mob_head#Mojang_skins) to create icons. I guess the uuid-like stuff in `ItemUtil.setSkullOwner()` is suppose to be player's UUID right? I have tried to [check those uuids](http://wiki.vg/Mojang_API#UUID_-.3E_Profile_.2B_Skin.2FCape) but they are invalid. If you want to obtain someone's UUID by name you can try something like `https://api.mojang.com/users/profiles/minecraft/MHF_ArrowLeft`.

I'm just guessing those thing. I have tried to take a look on `de.erethon.commons.item.ItemUtil`, but is working based on NMS which I have absolutely no idea of. Please correct me If I'm wrong.

**Comment by Sataniel98** [comment]
The fields are imported statically (import static de.erethon.commons.gui.GUIButton.*), which means they can be referred to without the class. I'd be surprised if this caused any differences on byte code level at all. The head util uses NMS to set Base64 encoded data to the head and they are taken from [here](https://freshcoal.com/maincollection). AFAIK the UUIDs aren't even necessary. This works well in various other plugins and it used to work in DXL as well. I guess that the issues occur somehow because of the relocation of de.erethon.commons to de.erethon.dungeonsxl.util.commons.

**Comment by Sataniel98** [comment]
Update: The error occurs even if the package isn't relocated. Still no idea what's wrong :/

**Comment by Sataniel98** [comment]
It turned out it happened because in 1.12, the item version of PLAYER_HEAD is called SKULL_ITEM and not SKULL...

_facepalm_
