### ISSUE TITLE
[bug] Ready sign doesn't work

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#411]
Hello,

I use the last vers of DXL. When i click on ready sign, i have this on console : 
[20:27:40 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.16-RC-01
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at de.erethon.dungeonsxl.sign.BlockSign.onInit(BlockSign.java:67) ~[?:?]
        at de.erethon.dungeonsxl.world.DGameWorld.startGame(DGameWorld.java:468) ~[?:?]
        at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:811) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:725) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:166) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:121) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:181) ~[?:?]
        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:113) ~[?:?]
        at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor449.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        ... 17 more

Any clue? :(

**Comment by Sataniel98** [comment]
It's either an erroneous block sign or a bug, and I definitely need to improve the error handling.

It would be very helpful if you could try it with this debugged build, please.

http://erethon.de/repo/de/erethon/dungeonsxl/0.16/dungeonsxl-0.16-SNAPSHOT-632-debug.jar

**Comment by Tiplish** [comment]
Hi, i try with the new build , one dungeon work and the other : 

[22:07:40 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.16-SNAPSHOT-632-debug
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-7754231-a3b3a42]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at de.erethon.dungeonsxl.world.DGameWorld.getStartLocation(DGameWorld.java:177) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.respawn(DGamePlayer.java:739) ~[?:?]
        at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:825) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:725) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:166) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:121) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:181) ~[?:?]
        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:113) ~[?:?]
        at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor372.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
        ... 17 more
:(

**Comment by Sataniel98** [comment]
Yeah I know, but it is supposed to print some debug lines when the dungeon loads or the game starts. Is there anything? For both dungeons including the one that seems to work?

Edit: Try this one please http://erethon.de/repo/de/erethon/dungeonsxl/0.16/dungeonsxl-0.16-SNAPSHOT-632-debug.jar , I marked the messages with a [DEBUG] prefix and included a (hopefully working) fix for the second one.

**Comment by Tiplish** [comment]
Ho i will try  ^^

**Comment by Tiplish** [comment]
[22:47:20 INFO]: -------- World Settings For [DXL_Game_0] --------
[22:47:20 INFO]: Mob Spawn Range: 4
[22:47:20 INFO]: Cactus Growth Modifier: 100%
[22:47:20 INFO]: Cane Growth Modifier: 100%
[22:47:20 INFO]: Melon Growth Modifier: 100%
[22:47:20 INFO]: Mushroom Growth Modifier: 100%
[22:47:20 INFO]: Pumpkin Growth Modifier: 100%
[22:47:20 INFO]: Sapling Growth Modifier: 100%
[22:47:20 INFO]: Wheat Growth Modifier: 100%
[22:47:20 INFO]: NetherWart Growth Modifier: 100%
[22:47:20 INFO]: Vine Growth Modifier: 100%
[22:47:20 INFO]: Cocoa Growth Modifier: 100%
[22:47:20 INFO]: Entity Activation Range: An 12 / Mo 24 / Mi 4
[22:47:20 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:47:20 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:47:20 INFO]: Random Lighting Updates: false
[22:47:20 INFO]: Structure Info Saving: true
[22:47:20 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[22:47:20 INFO]: Max TNT Explosions: 100
[22:47:20 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:47:20 INFO]: Item Despawn Rate: 6000
[22:47:20 INFO]: Item Merge Radius: 2.5
[22:47:20 INFO]: Arrow Despawn Rate: 1200
[22:47:20 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:47:20 INFO]: View Distance: 16
[22:47:20 INFO]: Zombie Aggressive Towards Villager: true
[22:47:20 INFO]: Experience Merge Radius: 3.0
[22:47:20 INFO]: Nerfing mobs spawned from spawners: false
[22:47:20 INFO]: Preparing start region for level 9 (Seed: 881642978533796370)
[22:47:20 INFO]: [dynmap] World 'DXL_Game_0' disabled

Nothing else :s

**Comment by Sataniel98** [comment]
Did you Ctrl. + F for "[DEBUG]"? And does everything work now (especially the block signs)?

**Comment by Tiplish** [comment]
One of my dungeon doesn't work (the same where i suppose that there is a problem of sign) so i have to suppress data before :p 

The others are ok.
