### ISSUE TITLE
spaming error movement in console 

### ISSUE THREAD

**Issue by Xeraccoon** [DRE2N/DungeonsXL#412]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Actual behavior

[17:20:50] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.16-RC-01
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at de.erethon.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:112) ~[dungeonsxl-0.16-RC-01.jar:?]
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	... 15 more

### Steps to reproduce

just move in game , the message is spammer all the time or have this moves

**Comment by Sataniel98** [comment]
Is there another stacktrace on startup? Can't reproduce this in a clean environment.

**Comment by Xeraccoon** [comment]
no idea but my cmd are spammed

**Comment by Sataniel98** [comment]
Then please tell me step by step how exactly you installed, loaded and used this plugin.

**Comment by Sataniel98** [comment]
Without any further information, I can only assume that this is because the plugin is loaded irregularly.
