### ISSUE TITLE
DXL reload

### ISSUE THREAD

**Issue by GGNoPotato** [DRE2N/DungeonsXL#425]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Reload dxl

### Actual behavior
`[20:50:27 INFO]: GGNoPotato issued server command: /dxl reload
[20:50:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.16-RC-01
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [paper_server.jar:git-TacoSpigot-"1be69cbf"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at de.erethon.dungeonsxl.global.GameSign.save(GameSign.java:122) ~[?:?]
        at de.erethon.dungeonsxl.global.GlobalProtectionCache.saveAll(GlobalProtectionCache.java:126) ~[?:?]
        at de.erethon.dungeonsxl.global.GlobalProtectionCache.saveAll(GlobalProtectionCache.java:108) ~[?:?]
        at de.erethon.dungeonsxl.DungeonsXL.saveData(DungeonsXL.java:250) ~[?:?]
        at de.erethon.dungeonsxl.DungeonsXL.onDisable(DungeonsXL.java:139) ~[?:?]
        at de.erethon.dungeonsxl.command.ReloadCommand.onExecute(ReloadCommand.java:93) ~[?:?]
        at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper_server.jar:git-TacoSpigot-"1be69cbf"]
        ... 15 more
`

### Steps to reproduce
Just typing /dxl reload

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)

**Comment by Sataniel98** [comment]
Is it possible that this is caused because you forcefully replaced a DXL sign with WorldEdit?

**Comment by Sataniel98** [comment]
Had a look at it, this is a duplicate of #419 and has already been fixed in 6a7f543c9e59058c246f65e810273357ec08cce5. Thank you for the report anyway :)
