### ISSUE TITLE
Mehrere Bugs

### ISSUE THREAD

**Issue by DuPleXFD** [DRE2N/DungeonsXL#43]
Mir ist aufgefallen das nicht alle Mobs funktionieren [Bspw der Wither und der Pig_zombie]. Er wird bei mir in der Config nicht übernommen. Ich weiss nicht ob es damit zusammenhängt, aber in einem test spuckte mir die console folgende Fehlermeldung aus:

[02:22:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.11-SNAPSHOT-28
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:945) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
    at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:148) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-2038f4a-cd36f6f]
    ... 18 more

Dazu kommt es noch, dass beim reloaden des plugins der dungeon erst nach einem reconnect auf dem server betreten werden kann. Der nether kann auch erst nach einem reconnect betreten werden. folgende fehlermeldung habe ich:

[02:34:46] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.11-SNAPSHOT-28
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-2038f4a-cd36f6f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
    at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:148) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-2038f4a-cd36f6f]
    ... 17 more

Auf dem ersten blick sieht sie gleich aus, aber ich habe mir sie nicht genauer angesehen.

Nach dem editieren des dungeons meldet er [ nach /dxl leave] das spieler &v1 nicht zur gruppe gehört.

ganze meldung: The player &v1 is not member of the group &v2&v4

das passiert bei allen dungeons die nach dem editieren verlassen werden. das beenden des editiermodus funktioniert erst mit ragequit oder /dxl escape

**Comment by Sataniel98** [comment]
So wie's aussieht, ist der Spieler nicht in DungeonsXL repräsentiert. Das repräsentierende Objekt sollte beim Betreten des Servers erstellt werden. Hast Du /reload zum Neustarten benutzt oder ein Plugin wie Plugman? In dem Falle könnten sie nicht erstellt werden. Wither und Pigmen sind eine Sache von Bukkit. Sie werden mit "PigZombie" und "WitherBoss" erkannt.

**Comment by Sataniel98** [comment]
Wither und Pigmen sind eine Sache von Bukkit. Sie werden mit "PigZombie" und "WitherBoss" erkannt.

**Comment by Sataniel98** [comment]
Das dürfte alles sein. Danke für die Meldung :) Build 31 enthält beide Fixes.
