### ISSUE TITLE
[Feature request]Add option to turn off update check

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#449]
Can we have an option to turn off update check please?

In some network, like us, have trouble with connecting other services due to firewall restriction. Also sometimes we don't want to enable auto update at all because that's where things starting to break, e.g. mismatched version or broken downloads without proper hash checks.

```
[02:13:17 WARN]: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
[02:13:17 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
[02:13:17 WARN]:        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
[02:13:17 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
[02:13:17 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
[02:13:17 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[02:13:17 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[02:13:17 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[02:13:17 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[02:13:17 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[02:13:17 WARN]:        at de.erethon.dungeonsxl.util.commons.update.spigot.SpigotUpdater.run(SpigotUpdater.java:131)
[02:13:17 WARN]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[02:13:17 WARN]:        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
[02:13:17 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
[02:13:17 WARN]:        ... 9 more
```

**Comment by Sataniel98** [comment]
I'm not Microsoft ^^ DungeonsXL doesn't update automatically to begin with, it just sends a message if you're running an outdated version, and that's it. It cannot break anything. Just noticed there's a newer updater that uses Spiget, so I might remake this anyway sooner or later.

**Comment by Sataniel98** [comment]
Resolved in the latest versions of DRECommons. Using one of the latest dev builds, you can disable the updater in the plugins/commons/config.yml.
