### ISSUE TITLE
Chest, signs, interact - Errors

### ISSUE THREAD

**Issue by Poweringg** [DRE2N/DungeonsXL#46]
I've got some errors when i opening chest, interacting with signs, typping commands etc.
i'm using spigot 1.9
# 

[21:07:44] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to DungeonsXL v0.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:735) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.EntityPlayer.openContainer(EntityPlayer.java:712) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.BlockChest.interact(SourceFile:340) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:515) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:880) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.ClassCastException: org.bukkit.block.DoubleChest cannot be cast to org.bukkit.block.Chest
    at io.github.dre2n.dungeonsxl.dungeon.game.GameChest.onOpenInventory(GameChest.java:105) ~[?:?]
    at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInventoryOpen(PlayerListener.java:509) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor242.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    ... 19 more
# 

[21:02:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:110) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:824) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.Error: Unresolved compilation problems: 
    IChatBaseComponent cannot be resolved to a type
    ChatSerializer cannot be resolved
    IChatBaseComponent cannot be resolved to a type
    ChatSerializer cannot be resolved
    PacketPlayOutTitle cannot be resolved to a type
    PacketPlayOutTitle cannot be resolved to a type
    EnumTitleAction cannot be resolved to a variable
    PacketPlayOutTitle cannot be resolved to a type
    PacketPlayOutTitle cannot be resolved to a type
    EnumTitleAction cannot be resolved to a variable
    PacketPlayOutTitle cannot be resolved to a type
    PacketPlayOutTitle cannot be resolved to a type
    EnumTitleAction cannot be resolved to a variable
    PacketPlayOutTitle cannot be resolved to a type
    PacketPlayOutTitle cannot be resolved to a type
    EnumTitleAction cannot be resolved to a variable
    PacketPlayOutTitle cannot be resolved to a type
    PacketPlayOutTitle cannot be resolved to a type
    PlayerConnection cannot be resolved to a type
    CraftPlayer cannot be resolved to a type
    CraftPlayer cannot be resolved to a type

```
at io.github.dre2n.dungeonsxl.util.messageutil.v1_9_R1.sendScreenMessage(v1_9_R1.java:19) ~[?:?]
at io.github.dre2n.dungeonsxl.util.messageutil.MessageUtil.sendScreenMessage(MessageUtil.java:225) ~[?:?]
at io.github.dre2n.dungeonsxl.util.messageutil.MessageUtil.sendScreenMessage(MessageUtil.java:240) ~[?:?]

at io.github.dre2n.dungeonsxl.player.DGroup.startGame(DGroup.java:233) ~[?:?]
at io.github.dre2n.dungeonsxl.player.DPlayer.ready(DPlayer.java:228) ~[?:?]
at io.github.dre2n.dungeonsxl.sign.ReadySign.ready(ReadySign.java:71) ~[?:?]
at io.github.dre2n.dungeonsxl.sign.ReadySign.onPlayerTrigger(ReadySign.java:50) ~[?:?]
at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:129) ~[?:?]
at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:85) ~[?:?]
at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:27) ~[?:?]
at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:231) ~[?:?]
at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
... 18 more
```
# 

[22:14:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1177) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_73]
    at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_73]
    at io.github.dre2n.dungeonsxl.dungeon.WorldConfig.load(WorldConfig.java:155) ~[?:?]
    at io.github.dre2n.dungeonsxl.dungeon.WorldConfig.<init>(WorldConfig.java:71) ~[?:?]
    at io.github.dre2n.dungeonsxl.dungeon.game.GameWorld.checkRequirements(GameWorld.java:408) ~[?:?]
    at io.github.dre2n.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:83) ~[?:?]
    at io.github.dre2n.dungeonsxl.listener.CommandListener.onCommand(CommandListener.java:51) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-f32adba-bf43ca6]
    ... 15 more

**Comment by Sataniel98** [comment]
It clearly says "[1.7.9-1.8.8]" in the description, v0.10 does not support CraftBukkit 1.9. You should try a [development build](http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/) of v0.11 instead :)
