### ISSUE TITLE
So many problems, i don't know where to start xD

### ISSUE THREAD

**Issue by tiradorus** [DRE2N/DungeonsXL#472]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Actual behavior

1- When you have a group (3 persons) Entering a dungeon, the leader leaves the dungeon with a sign [Leave] or just with /dxl leave, everyone is blocked inside, they can't leave the dungeon, even with /dxl leave that let them inside without any groups. They just can't go outside, exept if an admin Teleport them.
-------------------------------------------------------------------------------------------------------------------

2- Portals, damn so bugged bro. You create a portal (firstly the blocs aren't in the good direction, it create a multiple parallel portal), secondly if you enter into a dungeon with a portal, and leaves it, you are re-teleported into the portal. so you can't moove without re-being teleported into the dungeon. You can't escape exept if an administrator teleport you while you are locked into the portals.

-------------------------------------------------------------------------------------------------------------------

3 - The plugin make many java errors

-------------------------------------------------------------------------------------------------------------------

4 - If you have "Max instances : 2+" It create you infinite world, without reload them, you can create as much world as you want, the plugin saves them into the database, with only 1 person i can create 50+ worlds (Named as you know, "DXL_Game_0" but actually i create a "DXL_Game_57")
It create so many lags, why does a map, isn't instantanely removed while there is no one in, or just no group left?

### Expected behavior

1- When the group is being disbanded, All the grouped players inside the dungeon should be teleported outside and the dungeons should be closed.
OR, When the leaders leaves, the lead should be given to another grouped player. 

-------------------------------------------------------------------------------------------------------------------

2 - Portals should always be in the good direction, and a dungeon should have an exit spot that musn't be the entry spot ... it's a bit logic

-------------------------------------------------------------------------------------------------------------------

3 - it shouldn't

-------------------------------------------------------------------------------------------------------------------

4 - Empty dungeons may not exist.
I think an option like 'Time empty before removal : #sec' should be great.

### Steps to reproduce

1 -2 -3 - 4 : Steps are into the behavior.

### Explanation of the requested feature

All is into the behavior

### Possible use cases
-------------------------------------------------------------------------------------------------------------------
The server is on 1.8.8, that's maybe why some of thoses problems are present, but i don't had found a dungeon's version that allow 1.8 Minecrafts Versions.

Ps: There is the Java error.

`[23:36:17] [ERROR] Could not pass event PlayerInteractEvent to DungeonsXL v0.17
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:367) ~[?:?]
at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:333) ~[?:?]
at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:463) ~[?:?]
at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:441) ~[?:?]
at de.erethon.dungeonsxl.sign.LeaveSign.onPlayerTrigger(LeaveSign.java:77) ~[?:?]
at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:185) ~[?:?]
at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]
at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69) ~[?:?]
at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
... 17 more`

**Comment by Sataniel98** [comment]
Hi, please create one issue per issue in the future.

1. I'll have a look at this.

2. Portal directions are calculated by the facing direction of the creator.

3. Many...? You posted one. This is caused by a missing method in 1.8.x, I'll see if I can do anything about it.

4. They are removed in a task each minute. World manager plugins might prevent this.

**Comment by Sataniel98** [comment]
Please report again if the first and second issue happen again. They are most likely related to the third one, which I fixed.
