### ISSUE TITLE
"java.lang.NullPointerException" When I leave the dungeon

### ISSUE THREAD

**Issue by ProperSAMA** [DRE2N/DungeonsXL#481]
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Expected behavior
Leaving the dungeon safely

### Actual behavior
Die when I leave the dungeon

### Steps to reproduce
1./dxl play test
2.Commit suicide until the end of life or /dxl leave
3.Die and throw

[13:52:09 WARN]: java.lang.NullPointerException
[13:52:09 WARN]:        at de.erethon.dungeonsxl.util.commons.misc.ReflectionUtil.invoke(ReflectionUtil.java:191)
[13:52:09 WARN]:        at de.erethon.dungeonsxl.util.NBTUtil.getTag(NBTUtil.java:38)
[13:52:09 WARN]:        at de.erethon.dungeonsxl.util.NBTUtil.isDungeonItem(NBTUtil.java:102)
[13:52:09 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:371)
[13:52:09 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer.access$000(DGlobalPlayer.java:47)
[13:52:09 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer$1.run(DGlobalPlayer.java:329)
[13:52:09 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:52:09 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[13:52:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[13:52:09 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:52:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:52:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:52:09 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:52:09 INFO]: ProperSAMA died

**Comment by Sataniel98** [comment]
Hi, which version of DungeonsXL are you running?

**Comment by ProperSAMA** [comment]
v0.17.1
I downloaded it from SpigotMC

**Comment by ProperSAMA** [comment]
Now I download latest from http://erethon.de/repo/de/erethon/dungeonsxl/.The situation has not changed.

Steps to reproduce
1./dxl play test
2.Commit suicide until the end of life or /dxl leave
3.Die and throw

>[01:43:24 WARN]: java.lang.NullPointerException
[01:43:24 WARN]:        at de.erethon.dungeonsxl.util.commons.misc.ReflectionUtil.invoke(ReflectionUtil.java:191)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.util.NBTUtil.getTag(NBTUtil.java:38)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.util.NBTUtil.isDungeonItem(NBTUtil.java:102)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:371)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:333)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:463)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:441)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.sign.LeaveSign.onPlayerTrigger(LeaveSign.java:77)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:185)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50)
[01:43:24 WARN]:        at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69)
[01:43:24 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:43:24 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:43:24 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:43:24 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:43:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[01:43:24 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:43:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[01:43:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[01:43:24 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[01:43:24 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:43:24 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[01:43:24 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[01:43:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
[01:43:24 INFO]: ProperSAMA died
 

In /plugins/DungeonsXL/maps/xsmc/config.yml(xsmc is my dungeon name).My settings:
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true

If I set up keepInventory to false,the plugin not kill me and throw.But I have to use this function.

**Comment by Sataniel98** [comment]
Yeah, it didn't change because the latest version _is_ 0.17.1. I'll work on it! Thank you for the report.

**Comment by ProperSAMA** [comment]
thanks!

**Comment by Sataniel98** [comment]
Could you please test if it still happens in 0.17.2? The error should be fixed.

**Comment by ProperSAMA** [comment]
It didn't happen again when I first test.
But now...Let me test it again.

**Comment by ProperSAMA** [comment]
Oh I see.When my inventory is empty,it didn't happen again.
But if I have anything in my inventory,It will still happen.

> [06:37:23 WARN]: java.lang.NullPointerException
[06:37:23 WARN]:        at de.erethon.dungeonsxl.util.commons.misc.ReflectionUtil.invoke(ReflectionUtil.java:191)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.util.NBTUtil.getTag(NBTUtil.java:38)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.util.NBTUtil.isDungeonItem(NBTUtil.java:102)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:371)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:333)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:463)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:441)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.sign.LeaveSign.onPlayerTrigger(LeaveSign.java:77)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:185)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50)
[06:37:23 WARN]:        at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69)
[06:37:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:37:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:37:23 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:37:23 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[06:37:23 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[06:37:23 WARN]:        at pw.yumc.Yum.inject.ListenerInjector.execute(ListenerInjector.java:88)
[06:37:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:37:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[06:37:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[06:37:23 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[06:37:23 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:37:23 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[06:37:23 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[06:37:23 WARN]:        at java.lang.Thread.run(Thread.java:748)
[06:37:23 INFO]: ProperSAMA died

**Comment by Sataniel98** [comment]
Fixed! Please update to 0.17.3 :)

**Comment by ProperSAMA** [comment]
It didn't happen again!There should be no similar problem now.
