### ISSUE TITLE
Troubles spawning custom boss mob. 

### ISSUE THREAD

**Issue by nickswizle** [DRE2N/DungeonsXL#538]
**The feature you'd like to know more about**
externalMobProviders
[//]: # (e.g. game rules)

**Link to the wiki article (in case it exists)**
https://github.com/DRE2N/DungeonsXL/wiki/main-configuration
**What did you already try?**
I've tried different sign commands nothing seems to spawn the custom mob please help me idk what im doing wrong.
**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
externalMobProviders:
    # providerTag: spawn command
    # "%%"indicate placeholders
    BM: boss spawn %world% %x% %y% %z% %mob%

```

![halp](https://user-images.githubusercontent.com/40763864/52906871-48e53f00-321b-11e9-80e5-21f24dff16cf.png)

**Comment by Sataniel98** [comment]
Hi, is there some kind of console output when the mob is supposed to be spawned? "ExternalMob" signs are deprecated since they have been merged with mob signs. The signs look OK syntactically, but note that the position of the sign determines the mob's spawn point. Placing them on a wall might not work.

**Comment by nickswizle** [comment]
Thanks for the reply, I moved the sign off the wall and still nothing, I did notice a huge error in the console this time though. Here it is -

[20:02:09 ERROR]: Could not pass event WeatherChangeEvent to DungeonsXL v0.17.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.WorldData.setStorm(WorldData.java:519) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.setStorm(CraftWorld.java:907) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardWorldListener.initWorld(WorldGuardWorldListener.java:97) ~[worldguard-legacy-7.0.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardWorldListener.onWorldLoad(WorldGuardWorldListener.java:80) ~[worldguard-legacy-7.0.0-SNAPSHOT-dist.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:1008) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:462) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at de.erethon.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:225) ~[dungeonsxl-0.17.4.jar:?]
        at de.erethon.dungeonsxl.world.DResourceWorld.instantiateAsGameWorld(DResourceWorld.java:268) ~[dungeonsxl-0.17.4.jar:?]
        at de.erethon.dungeonsxl.command.TestCommand.onExecute(TestCommand.java:89) ~[dungeonsxl-0.17.4.jar:?]
        at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[dungeonsxl-0.17.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at de.erethon.dungeonsxl.world.DWorldListener.onWeatherChange(DWorldListener.java:190) ~[dungeonsxl-0.17.4.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-2aba349]
        ... 37 more

**Comment by Sataniel98** [comment]
Not likely related and not likely to cause problems, but I'll fix it when possible. Is your game initialized, did you set and trigger a ready sign?

**Comment by nickswizle** [comment]
I didn't set those signs yet I was using the /dxl test, I'll try right now and let you know. Thanks for the reply

**Comment by nickswizle** [comment]
I just tested playing it with all the signs and still nothing :(  Idk what im doing wrong..

**Comment by nickswizle** [comment]
Okay so I figured out World Guard was protecting plugins from spawning in mobs, I turned that off and now I get this in my console , is there a way to force whole numbers?

[10:39:38 INFO]: BOSS // Location must be a whole number (or ~ for your location)! Got: 88.5
[10:39:39 INFO]: BOSS // Location must be a whole number (or ~ for your location)! Got: 88.5

**Comment by Sataniel98** [comment]
Well, I see no good reason for a mob plugin to explicitly forbid decimals. Anyway, I've added new placeholders that are rounded to whole numbers, called %block_x% and so on. Use them instead in the main config.yml and it should work fine ;)

You can build DungeonsXL with the latest changes from source or get development builds [here](https://erethon.de/repo/de/erethon/dungeonsxl/). Please note that I'm currently moving the build repository to a new machine. It might take a few days until I've got everything working again and new builds show up.
