### ISSUE TITLE
[Bug] Players are ejected from the dungeon after death. 

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#546]
**Description**

When a player die in a dungeon, he is often put at the enter of the dungeon. He is not TP back in it. This problem occures since V0.17.5 from DXL and not before

**Reproduce**

Go in a dungeon, and DIE :p 

**Expected behavior**

Stay in the dungeon after death.

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```

```

**Comment by Sataniel98** [comment]
It does seem to be the case, I've found this stacktrace:
```
[18:57:47 WARN]: [DungeonsXL] Task #10 for DungeonsXL v0.17.6 generated an exception
java.lang.NullPointerException: null
        at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:640) ~[craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:622) ~[craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) ~[craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at de.erethon.dungeonsxl.util.commons.player.PlayerUtil.secureTeleport(PlayerUtil.java:89) ~[?:?]
        at de.erethon.dungeonsxl.player.RespawnTask.run(RespawnTask.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:833) [craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.2.jar:git-Bukkit-98b862a]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by Tiplish** [comment]
The last version of dxl is implemented since 8 days and the issue hasn't occured again :)
