### ISSUE TITLE
Internal Server Error when loading map after editing it

### ISSUE THREAD

**Issue by ColdSteamyShower** [DRE2N/DungeonsXL#549]
I am able to create and edit a map, but after I save and leave it, I am not able to load the map world again.

This is a blank map with no config, it also includes all required signs.

[01:56:12 INFO]: ColdSteamyShower issued server command: /dxl edit test2
[01:56:12 INFO]: -------- World Settings For [DXL_Edit_0] --------
[01:56:12 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[01:56:12 INFO]: Item Despawn Rate: 6000
[01:56:12 INFO]: Item Merge Radius: 2.5
[01:56:12 INFO]: Arrow Despawn Rate: 1200
[01:56:12 INFO]: View Distance: 10
[01:56:12 INFO]: Zombie Aggressive Towards Villager: true
[01:56:12 INFO]: Nerfing mobs spawned from spawners: false
[01:56:12 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[01:56:12 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[01:56:12 INFO]: Experience Merge Radius: 3.0
[01:56:12 INFO]: Mob Spawn Range: 4
[01:56:12 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[01:56:12 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[01:56:12 INFO]: Random Lighting Updates: false
[01:56:12 INFO]: Cactus Growth Modifier: 100%
[01:56:12 INFO]: Cane Growth Modifier: 100%
[01:56:12 INFO]: Melon Growth Modifier: 100%
[01:56:12 INFO]: Mushroom Growth Modifier: 100%
[01:56:12 INFO]: Pumpkin Growth Modifier: 100%
[01:56:12 INFO]: Sapling Growth Modifier: 100%
[01:56:12 INFO]: Beetroot Growth Modifier: 100%
[01:56:12 INFO]: Carrot Growth Modifier: 100%
[01:56:12 INFO]: Potato Growth Modifier: 100%
[01:56:12 INFO]: Wheat Growth Modifier: 100%
[01:56:12 INFO]: NetherWart Growth Modifier: 100%
[01:56:12 INFO]: Vine Growth Modifier: 100%
[01:56:12 INFO]: Cocoa Growth Modifier: 100%
[01:56:12 INFO]: Max TNT Explosions: 100
[01:56:12 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[01:56:12 INFO]: Preparing start region for level 3 (Seed: 1633942909676835157)
[01:56:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.17.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'dynmap' in plugin dynmap v2.3-1142
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:623) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at de.erethon.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:227) ~[?:?]
        at de.erethon.dungeonsxl.world.DResourceWorld.instantiateAsEditWorld(DResourceWorld.java:256) ~[?:?]
        at de.erethon.dungeonsxl.command.EditCommand.onExecute(EditCommand.java:67) ~[?:?]
        at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        ... 15 more
Caused by: java.lang.NullPointerException
        at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:937) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:623) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        at de.erethon.dungeonsxl.world.DResourceWorld.instantiate(DResourceWorld.java:227) ~[?:?]
        at de.erethon.dungeonsxl.world.DResourceWorld.instantiateAsEditWorld(DResourceWorld.java:256) ~[?:?]
        at de.erethon.dungeonsxl.command.EditCommand.onExecute(EditCommand.java:67) ~[?:?]
        at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-77ca7ca]
        ... 15 more

**Comment by Sataniel98** [comment]
Your Dynmap version is _three years old_. The error is thrown by it, update to the latest version and remember to keep it up to date in the future.
