### ISSUE TITLE
Issue with group signs in 1.14

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#564]
I am testing the plugin on 1.14 and everything seems to work fine except for creating a group sign.
When I create A group sign like this
[DXL]
Group
Zombie
1

it throws a null error for passing a signchangeevent to the plugin.
`[23:14:36] [Server thread/ERROR]: Could not pass event SignChangeEvent to DungeonsXL v0.17.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2407) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot.jar:git-Spigot-e4be9b0-5736cdc]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Attachable
        at de.erethon.dungeonsxl.global.JoinSign.onCreation(JoinSign.java:223) ~[?:?]
        at de.erethon.dungeonsxl.global.GroupSign.tryToCreate(GroupSign.java:217) ~[?:?]
        at de.erethon.dungeonsxl.global.GroupSign.tryToCreate(GroupSign.java:213) ~[?:?]
        at de.erethon.dungeonsxl.global.GlobalProtectionListener.onSignChange(GlobalProtectionListener.java:271) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[spigot.jar:git-Spigot-e4be9b0-5736cdc]
        ... 17 more`

**Comment by Sataniel98** [comment]
The plugin doesn't support 1.14.

**Comment by HauserGrim** [comment]
are you planning to support 1.14?

**Comment by Sataniel98** [comment]
Yes definitely, but I'm doing some changes to the project setup to better implement support for all versions. A new branch for this already exists: https://github.com/DRE2N/DungeonsXL/tree/multi-module

As I announced last month on my profile on spigotmc.org, no updates will be released before next month.

**Comment by Sataniel98** [comment]
Fixed.
