### ISSUE TITLE
Could not pass event SignChangeEvent

### ISSUE THREAD

**Issue by Kvosty** [DRE2N/DungeonsXL#588]
Hello, i have a problem with Group Sign. Everything works fine unless GROUP SIGN. My server version is Paper spigot 1.14.2, and plugin version is 0.18.. last dev build

error:

Could not pass event SignChangeEvent to DungeonsXL v0.18-SNAPSHOT-753 
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WALL_SIGN 
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_201] 
at org.bukkit.Material.valueOf(Material.java:83) ~[patched_1.14.2.jar:git-Paper-65] 
at de.erethon.caliburn.item.VanillaItem.getMaterial(VanillaItem.java:2156) ~[?:?] 
at de.erethon.dungeonsxl.global.JoinSign.onCreation(JoinSign.java:225) ~[?:?] 
at de.erethon.dungeonsxl.global.GroupSign.tryToCreate(GroupSign.java:217) ~[?:?] 
at de.erethon.dungeonsxl.global.GroupSign.tryToCreate(GroupSign.java:213) ~[?:?] 
at de.erethon.dungeonsxl.global.GlobalProtectionListener.onSignChange(GlobalProtectionListener.java:271) ~[?:?] 
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor562.execute(Unknown Source) ~[?:?] 
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65] 
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-65] 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65] 
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2599) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[patched_1.14.2.jar:git-Paper-65] 
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.2.jar:git-Paper-65] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201][39;0m

**Comment by Sataniel98** [comment]
It's not directly an issue in DungeonsXL but in the item library that doesn't yet support 1.14. It will be updated soon.

**Comment by Kvosty** [comment]
What type of library are you talking about?

**Comment by Kvosty** [comment]
i mean whats the name of it
