### ISSUE TITLE
Portal Bug

### ISSUE THREAD

**Issue by djlawrence4** [DRE2N/DungeonsXL#60]
This is nothing serious or it may be ... doesn't hinder my dungeons but a player decided to make a nether portal (Which is disabled) and a code popped up in the console log.

[18:49:19 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.11-SNAPSHOT-46
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:94) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:87) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.Entity.checkBlockCollisions(Entity.java:839) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.Entity.move(Entity.java:473) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.EntityLiving.g(EntityLiving.java:1644) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.EntityHuman.g(EntityHuman.java:1436) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.g(EntityHumanNPC.java:193) [citizens-2.0.17-SNAPSHOT.jar:?]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:319) [citizens-2.0.17-SNAPSHOT.jar:?]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:296) [citizens-2.0.17-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1612) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.World.g(World.java:1587) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:52) [citizens-2.0.17-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
        at io.github.dre2n.dungeonsxl.listener.PlayerListener.onInteract(PlayerListener.java:147) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-935f18b]
        ... 25 more

Thought it may be of importance to you.

**Comment by Sataniel98** [comment]
Thank you for the report! Your build is a bit outdated. This probably doesn't influence the error, but the details of the stacktrace. I'll try to reproduce and fix it :)

**Comment by Sataniel98** [comment]
Do you use any other portal plugins?

**Comment by djlawrence4** [comment]
Yes Multiverse-Portals.... as of right now I do not have any portals built... I only have one main world... but the issue started when a player tried to build their own portal (Their portal has no use but its good looks)

**Comment by Sataniel98** [comment]
I reproduced an error with portals, not entirely sure if it is this one, though xD Does the bug still occur in 0.11-SNAPSHOT-58?
