### ISSUE TITLE
 unknown error  and ready sign can't use

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#627]
**Description**

[//]: # (A clear and concise description of what the bug is.)

An unknown error is reported and the ready sign right-click is invalid
This error occurred when I opened isLobbyDisabled: true because ready sign was not available.

[//]: # (List steps to reproduce)

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
[23:21:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-SNAPSHOT-771
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1616]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1616]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1616]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1616]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1616]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoClassDefFoundError: io/github/dre2n/commandsxl/CommandsXL
	at de.erethon.dungeonsxl.sign.CommandSign.onInit(CommandSign.java:79) ~[?:?]
	at de.erethon.dungeonsxl.world.DGameWorld.startGame(DGameWorld.java:439) ~[?:?]
	at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:822) ~[?:?]
	at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:714) ~[?:?]
	at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:687) ~[?:?]
	at de.erethon.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:102) ~[?:?]
	at de.erethon.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:117) ~[?:?]
	at de.erethon.dungeonsxl.command.TestCommand.onExecute(TestCommand.java:95) ~[?:?]
	at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1616]
	... 15 more
```

**Comment by Sataniel98** [comment]
You are using a command sign without having CommandsXL installed.
