### ISSUE TITLE
Error with Ready Sign

### ISSUE THREAD

**Issue by Aeyori** [DRE2N/DungeonsXL#632]
**Description**
I'm getting an error with ready sign where it won't start or ready me when I click the sign. I got "Successfully created Dungeon sign" and the sign looks normal when I join the lobby, however I get an error in console when I right click it.
[//]: # (A clear and concise description of what the bug is.)

**Reproduce**

[//]: # (List steps to reproduce)

**Expected behavior**
Supposed to either have a countdown or start the dungeon.
[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
[20:46:03 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.18-SNAPSHOT-771
java.lang.NullPointerException: null
        at de.erethon.dungeonsxl.sign.ScriptSign.onInit(ScriptSign.java:50) ~[?:?]
        at de.erethon.dungeonsxl.world.DGameWorld.startGame(DGameWorld.java:439) ~[?:?]
        at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:822) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:714) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:161) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:117) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:185) ~[?:?]
        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]
        at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor700.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:440) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:991) ~[patched_1.14.4.jar:git-Paper-137]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by fatmanjumprope** [comment]
I'm also having this same issue. I was going to submit a ticket myself but figured it would be easier to just comment here. Most of the dungeon ready signs work well but 2 of them specifically when the ready sign is clicked will throw the same error as above.
