### ISSUE TITLE
Friend wanted to play a dungeon but got internal error message.

### ISSUE THREAD

**Issue by devingDev** [DRE2N/DungeonsXL#652]
**Description**

[//]: # (A clear and concise description of what the bug is.)

I told my friend to write /dxl play dungeon1 which i created before and also tried the same command i could enter without an error.
But when he did it it said something with internal error in minecraft chat.

```
[14:25:45] [Server thread/INFO]: TiirTV issued server command: /dxl play dungeon1
[14:25:45] [Server thread/INFO]: -------- World Settings For [DXL_Game_1] --------
[14:25:45] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:25:45] [Server thread/INFO]: Mob Spawn Range: 6
[14:25:45] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Carrot Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Potato Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Kelp Growth Modifier: 100%
[14:25:45] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[14:25:45] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:25:45] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[14:25:45] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[14:25:45] [Server thread/INFO]: Max TNT Explosions: 100
[14:25:45] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:25:45] [Server thread/INFO]: View Distance: 10
[14:25:45] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:25:45] [Server thread/INFO]: Item Merge Radius: 2.5
[14:25:45] [Server thread/INFO]: Item Despawn Rate: 6000
[14:25:45] [Server thread/INFO]: Arrow Despawn Rate: 1200
[14:25:45] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:25:45] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:25:45] [Server thread/INFO]: [WorldGuard] Default configuration file written: /home/thetiiringminecraftexperience/spigot/plugins/WorldGuard/worlds/DXL_Game_1/config.yml
[14:25:45] [Server thread/INFO]: [WorldGuard] Default configuration file written: /home/thetiiringminecraftexperience/spigot/plugins/WorldGuard/worlds/DXL_Game_1/blacklist.txt
[14:25:45] [Server thread/INFO]: [WorldGuard] (DXL_Game_1) TNT ignition is blocked.
[14:25:45] [Server thread/INFO]: [WorldGuard] (DXL_Game_1) Lighters are blocked.
[14:25:45] [Server thread/INFO]: [WorldGuard] (DXL_Game_1) Lava fire is blocked.
[14:25:45] [Server thread/INFO]: [WorldGuard] (DXL_Game_1) All fire spread is disabled.
[14:25:45] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'DXL_Game_1'
[14:25:45] [Server thread/INFO]: [QuickShop] Loading shops from the database...
[14:25:45] [Server thread/INFO]: [QuickShop] Used 1ms to fetch all shops from the database.
[14:25:45] [Server thread/INFO]: [QuickShop] Successfully loaded 0 shops! (Used 1ms, Avg 0ms per shop)
[14:25:45] [Server thread/INFO]: [QuickShop] 0 shops will load after chunk have loaded, 0 shops will load after the world has loaded.
[14:25:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-SNAPSHOT-771
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.yaml.snakeyaml.error.YAMLException: invalid string value has occurred
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentString.representData(SafeRepresenter.java:126) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:89) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:134) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:184) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:38) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:38) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:134) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:184) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at de.erethon.dungeonsxl.util.commons.config.DREConfig.save(DREConfig.java:122) ~[?:?]
	at de.erethon.dungeonsxl.player.DPlayerData.save(DPlayerData.java:536) ~[?:?]
	at de.erethon.dungeonsxl.player.DPlayerData.savePlayerState(DPlayerData.java:583) ~[?:?]
	at de.erethon.dungeonsxl.player.DInstancePlayer.<init>(DInstancePlayer.java:45) ~[?:?]
	at de.erethon.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:86) ~[?:?]
	at de.erethon.dungeonsxl.command.PlayCommand.onExecute(PlayCommand.java:98) ~[?:?]
	at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	... 17 more
[14:25:58] [Server thread/INFO]: bizzy93 issued server command: /dxl leave
[14:25:59] [Server thread/WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[14:25:59] [Server thread/WARN]: [Multiverse-Core] To let Multiverse know about it, use:
[14:25:59] [Server thread/WARN]: [Multiverse-Core] /mv import DXL_Game_0 NORMAL
[14:25:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DXL_Game_0): All chunks are saved
[14:26:01] [Server thread/INFO]: TiirTV issued server command: /dxl play dungeon1
[14:26:09] [Server thread/INFO]: TiirTV issued server command: /dxl leave
[14:26:10] [Server thread/WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[14:26:10] [Server thread/WARN]: [Multiverse-Core] To let Multiverse know about it, use:
[14:26:10] [Server thread/WARN]: [Multiverse-Core] /mv import DXL_Game_1 NORMAL
[14:26:10] [Server thread/INFO]: ThreadedAnvilChunkStorage (DXL_Game_1): All chunks are saved
[14:26:14] [Server thread/INFO]: TiirTV issued server command: /dxl play dungeon1
```

**Reproduce**

[//]: # (List steps to reproduce)

Just do /dxl play dungeon1

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

Well he being able to enter and play the dungeon like me.

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

```
config.yml of plugin : 

configVersion: 16
language: english
enableEconomy: false
chatEnabled: true
chatFormat:
  edit: '&2[Edit] &r%player_name%: '
  game: '&2[Game] %group_color%%player_name%: &r'
  group: '&2%group_color%[%group_name%] %player_name%: &r'
  spy: '&2[Chat Spy] %player_name%: &r'
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
- PINK
announcementInterval: 30.0
sendFloorTitle: true
globalDeathMessagesDisabled: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 10
secureMode:
  enabled: false
  openInventories: false
  dropItems: false
  checkInterval: 5.0
backupMode: ON_DISABLE_AND_SAVE
default: {}


config.yml of dungeon : 

message:
  '1': Welcome to the Beginner's dungeon! Don't be scared! Give it all you got!
secureObjects: []
invitedPlayers:
- 4d44ec50-6460-4cef-9322-9aa591b5542e

```

**Comment by Sataniel98** [comment]
I don't know why it happens, I'll add it to the to do list.

**Comment by devingDev** [comment]
umm so idk why but i had a suspicion so i made him do /clear
to clear his inventory and then it worked!

**Comment by Sataniel98** [comment]
This seems to be an internal problem with Bukkit's YAML library.
