### ISSUE TITLE
Unable to get 2 groups into the same PvP LMS game

### ISSUE THREAD

**Issue by Reaper0503** [DRE2N/DungeonsXL#717]
**Description**

Upon starting a PvP LMS game the second group is not teleported to the starting position resulting in them having unlimited lives.

**Expected behavior**

2 groups enter the map. Both choose a class and ready up. Both groups are teleported to opposite sides of the arena. Map is ended upon one player killing the other.

**Screenshots / GIFs / videos**

https://youtu.be/hafSifCWLOk

nb. I have also made a donation in hopes of getting donor support but I have no idea of how to claim it.

**Comment by Malfrador** [comment]
Stacktrace after clicking "Ready":
```[20:23:00 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.18-SNAPSHOT-819
java.lang.NullPointerException: null
        at de.erethon.dungeonsxl.player.DPlayerData.logTimeLastStarted(DPlayerData.java:424) ~[?:?]
        at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:833) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:714) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:161) ~[?:?]
        at de.erethon.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:117) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:184) ~[?:?]
        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]
        at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
        at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:469) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Tuinity-"bd5416d"]
        at java.lang.Thread.run(Thread.java:830) [?:?]```

**Comment by Sataniel98** [comment]
Thank you for the report, I'll work on it :)

**Comment by Sataniel98** [comment]
It seems to work fine in the latest build (956 at the time when I'm writing this). Could you please try it again and let me know if it works in your environment too?
