### ISSUE TITLE
NPE after leaving dungeon?

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#757]
Seemingly no problems, maybe rewards weren't given
```
[15:28:06 WARN]: [DungeonsXL] Task #129 for DungeonsXL v0.18-SNAPSHOT generated an exception
java.lang.NullPointerException: null
        at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:685) ~[patched_1.15.2.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:797) ~[patched_1.15.2.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:491) ~[patched_1.15.2.jar:git-Paper-162]
        at de.erethon.commons.player.PlayerUtil.secureTeleport(PlayerUtil.java:89) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:767) ~[?:?]
        at de.erethon.dungeonsxl.DungeonsXL$1.lambda$run$0(DungeonsXL.java:402) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_241]
        at de.erethon.dungeonsxl.DungeonsXL$1.run(DungeonsXL.java:402) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

**Comment by Sataniel98** [comment]
After leaving server:
```
[16:10:21 ERROR]: Could not pass event PlayerQuitEvent to DungeonsXL v0.18-SNAPSHOT
java.lang.NullPointerException: null
        at de.erethon.dungeonsxl.player.DPlayerListener.onPlayerQuit(DPlayerListener.java:426) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1130.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-162]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-162]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-162]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.PlayerList.disconnect(PlayerList.java:410) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.NetworkManager.handleDisconnection(NetworkManager.java:356) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:163) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-162]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```
Relog spawn was at a different location.
