### ISSUE TITLE
Compatibility Issue with Authme or WorldGuard? Not sure please help.

### ISSUE THREAD

**Issue by TheRealTamama** [DRE2N/DungeonsXL#760]
**Description**
Basically people get stuck in some limbo state (I guess its Authme plugin) after they disconnect in a dungeon and got kicked out of it and login on the portal block. The portal block would not let the player write in the chat to do the login command thats required... but here is the fun part, the log showed it had something to do with worldguard (check the log bellow). I will also be posting the same issue to the respective developers, please do share any solutions if this is a known issue.

**Reproduce**
1. Join Group and Join game.
2. Disconnect while in said game.
3. Get stuck in perpetual state of not being able to type and not being able to login.

**Tip: Having someone teleport you away before the limbo state allows you to use the /login command.

**Expected behavior**
Now I tried to fix this on the with Authme's configs by having the player teleport to spawn before they got Authenticated with the /login cmd which after they did it, teleports them back to their original location (outside the portal). But it didnt work... and i still got the perpetual get stuck inside the portal bug. 

**Relevant configuration files**

```
13.04 01:56:15 [Multicraft] Tamama ran command Message of the Day
13.04 01:56:20 [Server] ERROR Could not pass event PlayerTeleportEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e
13.04 01:56:20 [Server] INFO java.lang.NullPointerException: null
13.04 01:56:20 [Server] INFO at net.goldtreeservers.worldguardextraflags.wg.wrappers.AbstractRegionManagerWrapper.getRegion(AbstractRegionManagerWrapper.java:21) ~[?:?]
13.04 01:56:20 [Server] INFO at net.goldtreeservers.worldguardextraflags.wg.WorldGuardUtils.createFlagValueCalculator(WorldGuardUtils.java:89) ~[?:?]
13.04 01:56:20 [Server] INFO at net.goldtreeservers.worldguardextraflags.wg.WorldGuardUtils.queryValueUnchecked(WorldGuardUtils.java:68) ~[?:?]
13.04 01:56:20 [Server] INFO at net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnEntryFlagHandler.onCrossBoundary(TeleportOnEntryFlagHandler.java:48) ~[?:?]
13.04 01:56:20 [Server] INFO at net.goldtreeservers.worldguardextraflags.wg.wrappers.HandlerWrapper.onCrossBoundary(HandlerWrapper.java:59) ~[?:?]
13.04 01:56:20 [Server] INFO at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:209) ~[?:?]
13.04 01:56:20 [Server] INFO at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:169) ~[?:?]
13.04 01:56:20 [Server] INFO at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:416) ~[?:?]
13.04 01:56:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor428.execute(Unknown Source) ~[?:?]
13.04 01:56:20 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:765) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:489) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at de.erethon.dungeonsxl.util.commons.player.PlayerUtil.secureTeleport(PlayerUtil.java:89) ~[?:?]
13.04 01:56:20 [Server] INFO at de.erethon.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:112) ~[?:?]
13.04 01:56:20 [Server] INFO at de.erethon.dungeonsxl.global.DPortal.teleport(DPortal.java:261) ~[?:?]
13.04 01:56:20 [Server] INFO at de.erethon.dungeonsxl.global.GlobalProtectionListener.onPlayerMove(GlobalProtectionListener.java:155) ~[?:?]
13.04 01:56:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor402.execute(Unknown Source) ~[?:?]
13.04 01:56:20 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1103) ~[?:git-Paper-243]
13.04 01:56:20 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.14.4.jar:git-Paper-243]
13.04 01:56:20 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
```

**Comment by TheRealTamama** [comment]
Report update: OK i tried using water material for the portal and so i basically could do the login but somehow... im still in my group meaning i should still be in my game but AuthMe plugin teleported me to a location which I think its my last location in the dungeon. (Under the ocean lmao)

**Comment by Sataniel98** [comment]
Can't tell for sure at the moment. Maybe enabling secureMode in the main config helps?
