### ISSUE TITLE
[bug] Can't leave a group after joining it and can't join a dungeon or a player already in dungeon

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#761]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

After joining a group with the sign, i've try to use /dxl leave (without going in the dungeon). 

It's says that an internal error occure. 

**Reproduce**

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Join a group
3. Leave /dxl leave
4. Try to join another player with /dxl enter
5. see the spam error :(

**Expected behavior**

Leave the group without bug. 

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

**Error when trying to join a player with /dxl enter**

```
[18:00:09] [Server thread/INFO]: Tiplish issued server command: /dxl enter PudimDeBife
[18:00:09] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-SNAPSHOT-905
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paperspigot.jar:git-Paper-176]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paperspigot.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1058) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1051) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1122) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[paperspigot.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at de.erethon.dungeonsxl.command.EnterCommand.onExecute(EnterCommand.java:72) ~[?:?]
	at de.erethon.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paperspigot.jar:git-Paper-176]
	... 17 more
```

**Spam message in the console : **

```
[18:07:47] [Server thread/WARN]: [DungeonsXL] Task #1986493 for DungeonsXL v0.18-SNAPSHOT-905 generated an exception
java.lang.NullPointerException: null
	at de.erethon.dungeonsxl.sign.windup.DelayedPowerTask.run(DelayedPowerTask.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[paperspigot.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1211) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1132) ~[paperspigot.jar:git-Paper-176]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[paperspigot.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Sataniel98** [comment]
Don't think these two things are connected.

**Comment by Tiplish** [comment]
ok. Have you reproduce my bug ? Or do you need more details ?

**Comment by Sataniel98** [comment]
It's fine, I don't need to reproduce bugs that are documented with stacktraces. I think I've fixed it, but I'll test it before I publish it.
