### ISSUE TITLE
When porting to Dungeon using the Ready sign Wild plugin returns an error.

### ISSUE THREAD

**Issue by PhantumOne** [DRE2N/DungeonsXL#779]
**Description**

When porting to Dungeon using the Ready and End signs the Wild plugin returns an error (error does not occur when using the New Game sign or when using the "/dxl" commands even though I am ported to the same map (only when using Ready and Exit signs).

I have to use Multiverse because I am running multiple worlds
and I had to add Multiverse Inventories as a fix because your plugin would not let played enter a map with their inventory even if the Map config.yml was set to true for all KeepInventory variables. WildernessTP has features that other Wild plugins do not and has been on my server since day one with out any issues until now.  

I am using current versions Multiverse-Core v.4.1.0 (mc1.15), Multiverse Inventory v.3.0.0 (mc1.15) and Multiverse Portals v.4.1.0 (mc1.15) along with WildernessTP v.2.15 for (mc1.15) from these links:

https://dev.bukkit.org/projects/multiverse-core
https://dev.bukkit.org/projects/multiverse-portals/
https://dev.bukkit.org/projects/multiverse-inventories/
https://dev.bukkit.org/projects/wildernesstp-the-one-true-wildtp

**Reproduce**

I walk up to the Ready sign in my lobby and click it and I end up in the dungeon but my Server Console shows:

[13:07:06] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'DXL_Game_0'
[13:07:12] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Wild v2.15-a6aebd3
java.lang.NullPointerException: null
	at net.poweredbyhate.wildtp.WildSignListener.moneyOrNuttin(WildSignListener.java:121) ~[?:?]
	at net.poweredbyhate.wildtp.WildSignListener.isThisRealLife(WildSignListener.java:111) ~[?:?]
	at net.poweredbyhate.wildtp.WildSignListener.onClick(WildSignListener.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-208]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1379) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-208]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

![Dungeon Ready](https://user-images.githubusercontent.com/29824904/80523880-61d79d00-8954-11ea-837e-5ca177c25390.png)

And when I use the Exit Sign it show this in my Server Console:

[13:19:47] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Wild v2.15-a6aebd3
java.lang.NullPointerException: null
	at net.poweredbyhate.wildtp.WildSignListener.moneyOrNuttin(WildSignListener.java:121) ~[?:?]
	at net.poweredbyhate.wildtp.WildSignListener.isThisRealLife(WildSignListener.java:111) ~[?:?]
	at net.poweredbyhate.wildtp.WildSignListener.onClick(WildSignListener.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-208]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1379) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-208]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[13:23:15] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Wild v2.15-a6aebd3
java.lang.NullPointerException: null
	at net.poweredbyhate.wildtp.WildSignListener.moneyOrNuttin(WildSignListener.java:121) ~[?:?]
	at net.poweredbyhate.wildtp.WildSignListener.isThisRealLife(WildSignListener.java:111) ~[?:?]
	at net.poweredbyhate.wildtp.WildSignListener.onClick(WildSignListener.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-208]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-208]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1379) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-208]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-208]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

![Dungeon_Exit](https://user-images.githubusercontent.com/29824904/80524081-ad8a4680-8954-11ea-8a78-9f9e228629c7.png)

**Expected behavior**

no errors when performing it's functions

```

```

**Comment by Sataniel98** [comment]
This looks like any unknown world could cause this in the "Wild" plugin. Please report it to them.
