### ISSUE TITLE
An internal occurred ...

### ISSUE THREAD

**Issue by Malalicious** [DRE2N/DungeonsXL#78]
Hello,

I get the "An internal error occurred while attempting to perform this command" after creating a new dungeon and automatically porting into it. The server gives multiple errors as seen below:

`[18:48:55 INFO]: [DungeonsXL] World generation finished!

org.bukkit.command.CommandException: Unhandled exception executing command 'dxl'
 in plugin DungeonsXL v0.11.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-8a048fe-d8637df]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServe
r.java:646) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerCon
nection.java:1349) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java
:1184) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar
:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
26) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [spigot.jar:git-Spigot-8a048fe-d8637df]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 16.0

```
    at org.bukkit.craftbukkit.v1_9_R2.entity.CraftLivingEntity.setHealth(Cra
```

ftLivingEntity.java:95) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.clearPlayerData(DGamePl
ayer.java:147) ~[?:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java
:117) ~[?:?]
        at io.github.dre2n.dungeonsxl.command.CreateCommand.onExecute(CreateComm
and.java:98) ~[?:?]
        at io.github.dre2n.commons.command.BRCommandExecutor.onCommand(BRCommand
Executor.java:69) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-8a048fe-d8637df]
        ... 15 more`

This happens also when I edit an existing map.
I am using Spigot 1.9.4 (also tried 1.9) with DungeonsXL 0.11.3 (and tried the latest dev build as well).

**Comment by Sataniel98** [comment]
DungeonsXL used to use the old int health format for persistence, I hope this bug doesn't occur anymore with the double format.

Fix: https://github.com/DRE2N/DungeonsXL/commit/6b70e71abb85f9d8e0cc22211c072f5f2a319495

I'll upload a compiled jar as soon as possible.

**Comment by Sataniel98** [comment]
http://feuerstern.bplaced.net/repo/io/github/dre2n/dungeonsxl/0.11.4/ Does this work?

**Comment by Malalicious** [comment]
That fixed the issue, cheers.

**Comment by Sataniel98** [comment]
Glad to hear that :)
