### ISSUE TITLE
[BUG] Failed to read chunk data for task always crash my server

### ISSUE THREAD

**Issue by PeterMa9621** [DRE2N/DungeonsXL#783]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Sometimes this error will not occur, but sometimes this error occurs and crash my server. I am using Paper 1.15.2-211 and DungeonsXL #958. This error occurs when I am using #819, after updating, it's still there.

**Reproduce**

(List steps to reproduce, e.g.:
1. No idea how to reproduce it

**Expected behavior**

This error will not occur.

**Screenshots / GIFs / videos**
>[21:27:43] [Paper RegionFile IO Thread/FATAL]: Failed to read chunk data for task: Task for world: 'DXL_Game_35' at 5,-8 poi: false, hash: 256811050
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110) ~[?:1.8.0_252]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:715) ~[?:1.8.0_252]
	at net.minecraft.server.v1_15_R1.RegionFile.a(RegionFile.java:142) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.RegionFileCache.read(RegionFileCache.java:141) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.read(PlayerChunkMap.java:1234) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.WorldServer$2.readData(WorldServer.java:148) ~[patched_1.15.2.jar:git-Paper-211]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:557) ~[patched_1.15.2.jar:git-Paper-211]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.15.2.jar:git-Paper-211]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.15.2.jar:git-Paper-211]
[21:27:43] [Server thread/ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'DXL_Game_35', (5,-8), hashcode:350478042, priority: -1, file IO thread has dumped the relevant exception above
[21:27:47] [User Authenticator #35/INFO]: UUID of player Small_Baozi is d5a04325-aa25-3d87-abbe-12afe9d1f1fa
[21:27:53] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-211 (MC: 1.15.2) ---
[21:27:53] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[21:27:53] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:27:53] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:27:53] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[21:27:53] [Paper Watchdog Thread/ERROR]: 5,-8 in 'DXL_Game_35:
[21:27:53] [Paper Watchdog Thread/ERROR]: Load Task - none
[21:27:53] [Paper Watchdog Thread/ERROR]: Save Task - none
[21:27:53] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[21:27:53] [Paper Watchdog Thread/ERROR]: Chunk Status - null chunk
[21:27:53] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - null
[21:27:53] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:27:53] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[21:27:53] [Paper Watchdog Thread/ERROR]: 	PID: 19 | Suspended: false | Native: false | State: TIMED_WAITING
[21:27:53] [Paper Watchdog Thread/ERROR]: 	Stack:
[21:27:53] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:484)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.WorldServer.chunkCheck(WorldServer.java:865)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.Entity.setPosition(Entity.java:407)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.nms.v1_15_R1.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:202)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.teleport(CraftTextLine.java:133)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.object.CraftHologram.teleport(CraftHologram.java:351)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.object.CraftHologram.teleport(CraftHologram.java:318)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		chatBubble.ChatBubbleListener$1.run(ChatBubbleListener.java:61)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1233)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1151)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[21:27:53] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[21:27:53] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:27:53] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:27:53] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:27:58] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-211 (MC: 1.15.2) ---
[21:27:58] [Paper Watchdog Thread/ERROR]: The server has not responded for 15 seconds! Creating thread dump
[21:27:58] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:27:58] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:27:58] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[21:27:58] [Paper Watchdog Thread/ERROR]: 5,-8 in 'DXL_Game_35:
[21:27:58] [Paper Watchdog Thread/ERROR]: Load Task - none
[21:27:58] [Paper Watchdog Thread/ERROR]: Save Task - none
[21:27:58] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[21:27:58] [Paper Watchdog Thread/ERROR]: Chunk Status - null chunk
[21:27:58] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - null
[21:27:58] [Paper Watchdog Thread/ERROR]: ------------------------------
[21:27:58] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[21:27:58] [Paper Watchdog Thread/ERROR]: 	PID: 19 | Suspended: false | Native: false | State: TIMED_WAITING
[21:27:58] [Paper Watchdog Thread/ERROR]: 	Stack:
[21:27:58] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:484)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.WorldServer.chunkCheck(WorldServer.java:865)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.Entity.setPosition(Entity.java:407)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.nms.v1_15_R1.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:202)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.teleport(CraftTextLine.java:133)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.object.CraftHologram.teleport(CraftHologram.java:351)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		com.gmail.filoghost.holographicdisplays.object.CraftHologram.teleport(CraftHologram.java:318)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		chatBubble.ChatBubbleListener$1.run(ChatBubbleListener.java:61)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1233)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1151)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[21:27:58] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment]
Thank you for the report, I'm sorry for the late reply. The plugin that throws the error is a chat bubble plugin. It only happens in a world generated by DungeonsXL, which is technically no different to any other world.
