### ISSUE TITLE
Error dying in dungeon

### ISSUE THREAD

**Issue by SwimUp** [DRE2N/DungeonsXL#788]
Hey. An error appears in the console when I die in a dungeon.
Spigot 1.15.2
Dungeon rev 960 (last at the moment)

Dungeon config:
```
# GAME RULES #
isLobbyDisabled: false
timeUntilKickOfflinePlayer: 10000
timeToFinish: -1
gameMode: ADVENTURE
fly: false
playerVersusPlayer: false
friendlyFire: false
gameCommandWhitelist:
- version
- f list
- f show
- ch global
timeLastPlayed: 336
keepInventoryOnEnter: true
keepInventoryOnDeath: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
breakBlocks: false
breakPlacedBlocks: true
breakWhitelist: []
damageProtectedEntities:
- SLIME
- PAINTING
interactionProtectedEntities:
- ARMOR_STAND
placeBlocks: false
placeWhitelist:
- SPONGE
initialLives: 1
initialGroupLives: 1
messages:
  '0': '&6Мертвые копи<br>&aМакс.игроков: 3<br>&aУровень: 10'
  '1': '&aЧтобы пройти<br>Убейте §4۞ §6Кости странника [10ур] §4۞'
secureObjects:
- 69
title:
  title: '&4Мертвые копи'
  fadeIn: 1.0
  show: 3.0
  fadeOut: 1.0
rain: false
thunder: false
time: 20000
invitedPlayers:
- 1e757563-cafc-3378-8279-b91f6a710711
```

```
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:450) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot.jar:git-Spigot-2040c4c-1872231]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-2040c4c-1872231]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
	at de.erethon.dungeonsxl.trigger.TriggerListener.onPlayerInteract(TriggerListener.java:92) ~[dungeonsxl-dist-0.18-SNAPSHOT-960.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-2040c4c-1872231]
	... 19 more
```

**Comment by Sataniel98** [comment]
This is a problem in the item library that will be resolved without changes in DXL in the midterm when the shaded lib is updated. It has nothing to do with players dying though, the error is in an interaction listener (when players right or left click something).

Anyway, thank you very much for the report.
