### ISSUE TITLE
Can't edit dungeon

### ISSUE THREAD

**Issue by Darwin1546** [DRE2N/DungeonsXL#809]
**Description**
I'm just download DungeonsXL and ran into problen instatly

**Reproduce**
1. /dxl create ot /dxl edit with non vanilla health (i think)

```
[17:30:28] [Server thread/INFO]: Darwinian issued server command: /dxl create CantoXIII
[17:30:28] [Server thread/INFO]: [DungeonsXL] Creating new map.
[17:30:28] [Server thread/INFO]: [DungeonsXL] Generating new world...
[17:30:28] [Server thread/INFO]: [WorldGuard] Default configuration file written: D:\Owlcraft\MMO114\plugins\WorldGuard\worlds\DXL_Edit_0\config.yml
[17:30:28] [Server thread/INFO]: [WorldGuard] Default configuration file written: D:\Owlcraft\MMO114\plugins\WorldGuard\worlds\DXL_Edit_0\blacklist.txt
[17:30:28] [Server thread/INFO]: [DungeonsXL] World generation finished.
[17:30:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-SNAPSHOT-968
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 10.050000190734863(20.0)
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:108) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at de.erethon.dungeonsxl.player.DInstancePlayer.clearPlayerData(DInstancePlayer.java:77) ~[?:?]
        at de.erethon.dungeonsxl.player.DEditPlayer.<init>(DEditPlayer.java:55) ~[?:?]
        at de.erethon.dungeonsxl.command.CreateCommand.onExecute(CreateCommand.java:92) ~[?:?]
        at de.erethon.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        ... 17 more
```

**Comment by Sataniel98** [comment]
Which plugin sets the health?

**Comment by Darwin1546** [comment]
MMOCore

**Comment by fillnati** [comment]
how it repair?

**Comment by OOO6704** [comment]
I want to know how to repair too
