### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mooklate** [DRE2N/DungeonsXL#842]
18:53:22 ERROR]: Error occurred while enabling DungeonsXL v0.18-SNAPSHOT-1003 (Is it up to date?)
java.lang.IllegalArgumentException: The permission dxl.announce is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:724) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:716) ~[patched_1.15.2.jar:git-Paper-366]
        at de.erethon.dungeonsxl.player.DPermission.register(DPermission.java:213) ~[?:?]
        at de.erethon.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:214) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-366]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1866) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1674) ~[patched_1.15.2.jar:git-Paper-366]
        at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
        at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
        at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-366]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Sataniel98** [comment]
Don't use PlugMan.
