### ISSUE TITLE
Bug with RewardChest

### ISSUE THREAD

**Issue by OMR2K** [DRE2N/DungeonsXL#867]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**
When a group get reward chests, then they end the dungeon, I get an error when in opens the "treasures" chest after the dungeon.

(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**

(List steps to reproduce, e.g.:
1. Place RewardChest signs on chests
2. End the dungeon (by triggering an [End] sign)

**Expected behavior**
Expected behavior is that the rewards from the rewards chests from the dungeon show up in the "Treasures" GUI after the dungeon ends, however, nothing is in the GUI (except glass, next page, previous page {you can take out these items}) and I get the following error in console.

```
20.07 22:08:44 [Server] WARN [DungeonsXL] Task #60913 for DungeonsXL v0.18-SNAPSHOT-1004 generated an exception
20.07 22:08:44 [Server] INFO java.lang.IllegalArgumentException: Cannot measure distance between world and DXL_Game_7
20.07 22:08:44 [Server] INFO at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at de.erethon.dungeonsxl.trigger.DistanceTrigger.triggerAllInDistance(DistanceTrigger.java:82) ~[?:?]
20.07 22:08:44 [Server] INFO at de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:805) ~[?:?]
20.07 22:08:44 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL$2.lambda$run$0(DungeonsXL.java:392) ~[?:?]
20.07 22:08:44 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_242]
20.07 22:08:44 [Server] INFO at de.erethon.dungeonsxl.DungeonsXL$2.run(DungeonsXL.java:392) ~[?:?]
20.07 22:08:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
20.07 22:08:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Sataniel98** [comment]
Should be resolved
