### ISSUE TITLE
Can't join the dungeon using portals

### ISSUE THREAD

**Issue by morjanmihail** [DRE2N/DungeonsXL#873]
Hello,

   I created a dungeon and worked everything until I created a sign for groups and portal for it. Having one error in Paper Spigot 1.15.2:

`[17:03:01 ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1003
java.lang.NullPointerException: null
	at de.erethon.dungeonsxl.requirement.ForbiddenItemsRequirement.getCheckMessage(ForbiddenItemsRequirement.java:94) ~[?:?]
	at de.erethon.dungeonsxl.api.event.requirement.RequirementCheckEvent.<init>(RequirementCheckEvent.java:44) ~[?:?]
	at de.erethon.dungeonsxl.player.DGlobalPlayer.checkRequirements(DGlobalPlayer.java:287) ~[?:?]
	at de.erethon.dungeonsxl.global.DPortal.teleport(DPortal.java:256) ~[?:?]
	at de.erethon.dungeonsxl.global.GlobalProtectionListener.onPlayerMove(GlobalProtectionListener.java:165) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor720.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-384]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-384]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-384]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1153) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-384]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
`

   Can anyone help me with this?

Kind regards,
Mihai

**Comment by Virologicbody** [comment]
Same error in Paper 1.16.1

Plugin basically unusable unless I am OP

**Comment by Ancard** [comment]
Spigot 1.16.3
Papper Spigot 1.16.3

`[Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1030
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
	at de.erethon.dungeonsxl.requirement.ForbiddenItemsRequirement.getCheckMessage(ForbiddenItemsRequirement.java:94) ~[?:?]
	at de.erethon.dungeonsxl.api.event.requirement.RequirementCheckEvent.<init>(RequirementCheckEvent.java:44) ~[?:?]
	at de.erethon.dungeonsxl.player.DGlobalPlayer.checkRequirements(DGlobalPlayer.java:290) ~[?:?]
	at de.erethon.dungeonsxl.global.DPortal.teleport(DPortal.java:256) ~[?:?]
	at de.erethon.dungeonsxl.global.GlobalProtectionListener.onPlayerMove(GlobalProtectionListener.java:165) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]
	... 18 more`

**Comment by Sataniel98** [comment]
@Ancard This is an entirely different error, please make a new issue and fill out the template.

**Comment by Sataniel98** [comment]
Fixed
