### ISSUE TITLE
java.lang.IllegalStateException: Removing entity while ticking!

### ISSUE THREAD

**Issue by eDexiam** [DRE2N/DungeonsXL#876]
**Description**
This error occured in my console at some point while testing a dungeon in a group
[21:54:27 ERROR]: [Minecraft] Could not pass event EntityDeathEvent to DungeonsXL v0.18-SNAPSHOT-1003
```
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1520) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.WorldServer.removePlayer(WorldServer.java:1540) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:681) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:807) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:492) ~[patched_1.15.2.jar:git-Paper-385]
        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:461) ~[?:?]
        at de.erethon.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:454) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:380) ~[?:?]
        at de.erethon.dungeonsxl.player.DGroup.lambda$finish$2(DGroup.java:603) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_265]
        at de.erethon.dungeonsxl.player.DGroup.finish(DGroup.java:603) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:600) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:585) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.finishFloor(DGamePlayer.java:554) ~[?:?]
        at de.erethon.dungeonsxl.sign.button.EndSign.push(EndSign.java:127) ~[?:?]
        at de.erethon.dungeonsxl.api.sign.Button.lambda$push$0(Button.java:45) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265]
        at de.erethon.dungeonsxl.api.sign.Button.push(Button.java:45) ~[?:?]
        at de.erethon.dungeonsxl.api.sign.Button.trigger(Button.java:76) ~[?:?]
        at de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:188) ~[?:?]
        at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]
        at de.erethon.dungeonsxl.trigger.MobTrigger.onTrigger(MobTrigger.java:45) ~[?:?]
        at de.erethon.dungeonsxl.mob.DMob.onDeath(DMob.java:141) ~[?:?]
        at de.erethon.dungeonsxl.mob.DMobListener.onEntityDeath(DMobListener.java:71) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor938.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-385]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767) ~[patched_1.15.2.jar:git-Pap
er-385]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:808) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.World.a(World.java:879) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:532) ~[patched_1.15.2.jar:git-Paper-385]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1328) ~[patched_1.15.2.jar:git-Paper-385]
```

**Reproduce**

Unsure

**Expected behavior**

No error

**Comment by Sataniel98** [comment]
Thank you for the report.
