### ISSUE TITLE
ERROR: Could not pass event PlayerMoveEvent to DungeonsXL

### ISSUE THREAD

**Issue by Moleculatorul** [DRE2N/DungeonsXL#894]
**Description**

I`m using: 

This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

If you do a normal dungeon without floors everything is flawless.
When i create the config.yml file and paste the floor configuration, the portal stops working and i get the error i posted at the end of this message.
If i remove the config file or just the code inside it everything works again.

**Reproduce**
1. Create a new dungeon with /dxl create
2. Place 
1st floor=
[lobby] sign
[ready] sign
[start] sign
[mob] zombie 3,5 D 13 sign
[mob] Skeleton 3,5 D 13  sign
[mob] Evoker 2,1 D 5 sign
2nd floor=
[teleport]      M Evoker sign
[Checkpoint] D 2
[Leave] sign

3. Leave edit mode with /dxl save +/dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of all signs and they all do work

**Expected behavior**
I wanted that when you kill the evoker to automaticlly teleport you to the second floor(2nd floor not completed yet i want to add more mob signs)

The following error multiplies in the console every time i interact with the portal, it`s the same error all over, again and again

```
[12:23:23] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1003
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at de.erethon.dungeonsxl.requirement.ForbiddenItemsRequirement.getCheckMessage(ForbiddenItemsRequirement.java:94) ~[?:?]
        at de.erethon.dungeonsxl.api.event.requirement.RequirementCheckEvent.<init>(RequirementCheckEvent.java:44) ~[?:?]
        at de.erethon.dungeonsxl.player.DGlobalPlayer.checkRequirements(DGlobalPlayer.java:287) ~[?:?]
        at de.erethon.dungeonsxl.global.DPortal.teleport(DPortal.java:256) ~[?:?]
        at de.erethon.dungeonsxl.global.GlobalProtectionListener.onPlayerMove(GlobalProtectionListener.java:165) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
        ... 18 more
```

**Comment by Sataniel98** [comment]
Should be resolved in build 1026 and higher. If you still have issues, please let me know.
