### ISSUE TITLE
Group-Game combination crashes and not work properly.

### ISSUE THREAD

**Issue by GuazP** [DRE2N/DungeonsXL#903]
**Description**

Generally I created dungeon entrance presented on screen.... 
There are 4 groups signs and one game sign for dungeon, to create pvp area. 
Different groups have different spawns ([start] 0-3) and beds ([bed] 0-3).
This generally don't work because groups didn't see each other when I want and configured dungeon to create pvp arena.

But with old bedwars map sended by Sataniel, groups see each other properly, and there pvp is possible after I added config.yml. So I used it to create my arena again.

**Reproduce**

1. Launch that dungeon: ` https://erethon.de/resources/dxl/Bedwars.zip `, or create other one with 4 beds (with proper 4 bed signs), 4 starts (with proper signs), ( [ready] Bedwars ) sign in lobby and one [leave] sign.
2. Place 4 groups signs:
- [dxl]
- group
- bedwars
- 4
3. Place one game sign:
- [dxl]
- game
- bedwars
- 4
4. Create a portal
5. Atleast two players should enter to game, and click ready, then someone new during the game should join other or the same group like one of them. Then dungeons when this player click ready produce a hug lag. Generally only restart help, and then people lost their equipment their had before their enter dungeon. 
[It's high severity for server with complicated crafting system where literally you can forge your gear for over few hours to smelt proper resources]

**Expected behavior**

Generally I would like to block all groups and game itself like it works with normal pve dungeons, when group sign is used in combination with game sign.
Or, restart signs when all people get ready and start game - it should close option to join for other people.
Also if I do something wrong, I would like to have at least one example how to make pvp arena or bedwars, I could even as my pay back prepare wideo for you for such introduction how to obtain it (lethal) bug-free. 

**Screenshots / GIFs / videos**

My configuration of signs outside dungeon:
https://imgur.com/3GtCenX

Whole dungeon folder:
https://www.dropbox.com/s/9yf4zhgamsk6jgu/pvp_iron.rar?dl=0

**Relevant configuration files**

```
playerVersusPlayer: true
friendlyFire: false
breakBlocks: false
breakPlacedBlocks: true

damageProtectedEntities:
- PAINTING

interactionProtectedEntities:
- ARMOR_STAND

initialLives: 3

time: 200
```

**Comment by GuazP** [comment]
Ah, generally when during this broke I tried to dxl kick someone or dxl reload, following message occurs:
`An internal error occured while attempting to perform this command`

```
[20:53:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command "dxl" in plugin DungeonsXL v0.18-SNAPSHOT-1020
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at de.erethon.dungeonsxl.command.LeaveCommand.onExecute(LeaveCommand.java:59) ~[?:?]
at de.erethon.dungeonsxl.command.KickCommand.onExecute(KickCommand.java:48) ~[?:?]
at de.erethon.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
... 18 more
[20:53:53] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1020
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at de.erethon.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:126) ~[?:?]
at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
... 18 more
[20:53:53] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1020
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at de.erethon.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:126) ~[?:?]
at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
... 18 more
[20:53:53] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1020
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at de.erethon.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:126) ~[?:?]
at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
... 18 more
[20:53:53] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to DungeonsXL v0.18-SNAPSHOT-1020
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1005) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at de.erethon.dungeonsxl.reward.RewardListener.onPlayerMove(RewardListener.java:126) ~[?:?]
at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-17d78db-f8d4da0]
... 18 more
```
