### ISSUE TITLE
I found errors...ver 0.12

### ISSUE THREAD

**Issue by AngelCatOwO** [DRE2N/DungeonsXL#92]
[11:02:43 ERROR]: Could not pass event EntityDamageByEntityEvent to DungeonsXL v
0.12
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(Craf
tEventFactory.java:87) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6
f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDama
geEvent(CraftEventFactory.java:553) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-d
b6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDa
mageEvent(CraftEventFactory.java:466) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot
-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEn
tityDamageEvent(CraftEventFactory.java:585) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-
Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [
spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.j
ava:743) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster
.java:42) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001
) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:10
63) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:1355) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [
spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [
spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8
.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.get
ItemInMainHand()Lorg/bukkit/inventory/ItemStack;
        at io.github.dre2n.dungeonsxl.util.caliburn.listener.EntityListener.onDa
mageByPlayer(EntityListener.java:50) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-db6de12-d3e0b6f]
        ... 24 more

**Comment by Sataniel98** [comment]
Thank you for the report, I'll fix it right after breakfast :)

**Comment by Sataniel98** [comment]
Fixed it in 0.12.1-SNAPSHOT build 1
