### ISSUE TITLE
Dungeon Floor BUG

### ISSUE THREAD

**Issue by HuJunwei23333** [DRE2N/DungeonsXL#943]
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**The floor dungeon can only complete the last floor, but not the dungeon, and cannot delete the game map (DXL_Game_0, DXL_Game_1...) in the server folder.

(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

**Reproduce**The floor dungeon can only complete the last floor, but not the dungeon, and cannot delete the game map (DXL_Game_0, DXL_Game_1...) in the server folder.

(List steps to reproduce, e.g.:
Java: Java SE Runtime Environment 8u261 
server: paper-1.16.4-312.jar
1. Test with /dxl play
2. Complete the last floor of the dungeon
3.Console warning
`[20:23:09 WARN]: [DungeonsXL] Task #4618 for DungeonsXL v0.18-SNAPSHOT-1063 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between map and DXL_Game_10
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.4.jar:git-Paper-312]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.4.jar:git-Paper-312]
        at de.erethon.dungeonsxl.trigger.DistanceTrigger.triggerAllInDistance(DistanceTrigger.java:82) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.update(DGamePlayer.java:812) ~[?:?]
        at de.erethon.dungeonsxl.DungeonsXL$2.lambda$run$0(DungeonsXL.java:404) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261]
        at de.erethon.dungeonsxl.DungeonsXL$2.run(DungeonsXL.java:404) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-312]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-312]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-312]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-312]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-312]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-312]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

**Expected behavior**

(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**
![PM)HA7F{%0(5LJ~$EJ9APFQ](https://user-images.githubusercontent.com/30760975/101353156-10e53b00-388b-11eb-8352-ba8d662a4680.png)

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**
[DungeonsXLXLXL.zip](https://github.com/DRE2N/DungeonsXL/files/5652741/DungeonsXLXLXL.zip)

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by HuJunwei23333** [comment]
Single floor dungeon can be completed normally

**Comment by Sataniel98** [comment]
Thank you for the report. I don't know when I'll have time to look at it but I definitely will.
